export interface CountryInfo {
  code: string; // ISO 3166-1 alpha-2 code e.g. "US"
  name: string; // Country Name e.g. "United States"
  flag: string; // Emoji Flag e.g. "🇺🇸"
  phoneCode: string; // International Dialing Code e.g. "+1"
  phoneLength: number | number[]; // Standard phone digits length(s)
  currencyCode: string; // Official Currency Code e.g. "USD"
  currencySymbol: string; // Official Currency Symbol e.g. "$"
  currencyPosition: "prefix" | "suffix"; // Placement of currency symbol
  decimalDigits: number; // Decimal precision (0 for JPY, 3 for KWD, 2 for USD)
  timeZone: string; // Standard default IANA Timezone
  dateFormat: string; // Default standard date format
  taxName: string; // Statutory tax system name e.g. "Sales Tax", "VAT", "GST", "TVA"
  taxIdLabel: string; // Statutory registration label e.g. "Tax ID / EIN", "VAT No.", "GSTIN"
  defaultTaxRate: number; // Standard statutory tax rate (%)
}

export const COUNTRIES: CountryInfo[] = [
  // --- North America ---
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    phoneCode: "+1",
    phoneLength: 10,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "America/New_York",
    dateFormat: "MM/DD/YYYY",
    taxName: "Sales Tax",
    taxIdLabel: "EIN / Tax ID",
    defaultTaxRate: 7.5,
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    phoneCode: "+1",
    phoneLength: 10,
    currencyCode: "CAD",
    currencySymbol: "C$",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "America/Toronto",
    dateFormat: "YYYY-MM-DD",
    taxName: "GST / HST",
    taxIdLabel: "Business Number (BN)",
    defaultTaxRate: 13,
  },
  {
    code: "MX",
    name: "Mexico",
    flag: "🇲🇽",
    phoneCode: "+52",
    phoneLength: 10,
    currencyCode: "MXN",
    currencySymbol: "Mex$",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "America/Mexico_City",
    dateFormat: "DD/MM/YYYY",
    taxName: "IVA",
    taxIdLabel: "RFC (Registro Federal)",
    defaultTaxRate: 16,
  },

  // --- Europe ---
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    phoneCode: "+44",
    phoneLength: 10,
    currencyCode: "GBP",
    currencySymbol: "£",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Europe/London",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "VAT Registration No.",
    defaultTaxRate: 20,
  },
  {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    phoneCode: "+49",
    phoneLength: [10, 11],
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Berlin",
    dateFormat: "DD.MM.YYYY",
    taxName: "MwSt",
    taxIdLabel: "USt-IdNr / Steuer-Nr",
    defaultTaxRate: 19,
  },
  {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    phoneCode: "+33",
    phoneLength: 9,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Paris",
    dateFormat: "DD/MM/YYYY",
    taxName: "TVA",
    taxIdLabel: "Numéro TVA / SIRET",
    defaultTaxRate: 20,
  },
  {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    phoneCode: "+34",
    phoneLength: 9,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Madrid",
    dateFormat: "DD/MM/YYYY",
    taxName: "IVA",
    taxIdLabel: "NIF / CIF / IVA",
    defaultTaxRate: 21,
  },
  {
    code: "IT",
    name: "Italy",
    flag: "🇮🇹",
    phoneCode: "+39",
    phoneLength: 10,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Rome",
    dateFormat: "DD/MM/YYYY",
    taxName: "IVA",
    taxIdLabel: "Partita IVA (P.IVA)",
    defaultTaxRate: 22,
  },
  {
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    phoneCode: "+31",
    phoneLength: 9,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Europe/Amsterdam",
    dateFormat: "DD-MM-YYYY",
    taxName: "BTW",
    taxIdLabel: "Btw-identificatienummer",
    defaultTaxRate: 21,
  },
  {
    code: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    phoneCode: "+32",
    phoneLength: 9,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Europe/Brussels",
    dateFormat: "DD/MM/YYYY",
    taxName: "TVA / BTW",
    taxIdLabel: "Numéro TVA / Ondernemingsnr",
    defaultTaxRate: 21,
  },
  {
    code: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
    phoneCode: "+41",
    phoneLength: 9,
    currencyCode: "CHF",
    currencySymbol: "CHF",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Europe/Zurich",
    dateFormat: "DD.MM.YYYY",
    taxName: "MWST / TVA",
    taxIdLabel: "UID / MWST-Nummer",
    defaultTaxRate: 8.1,
  },
  {
    code: "AT",
    name: "Austria",
    flag: "🇦🇹",
    phoneCode: "+43",
    phoneLength: [10, 11],
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Vienna",
    dateFormat: "DD.MM.YYYY",
    taxName: "USt (MwSt)",
    taxIdLabel: "UID-Nummer",
    defaultTaxRate: 20,
  },
  {
    code: "SE",
    name: "Sweden",
    flag: "🇸🇪",
    phoneCode: "+46",
    phoneLength: 9,
    currencyCode: "SEK",
    currencySymbol: "kr",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Stockholm",
    dateFormat: "YYYY-MM-DD",
    taxName: "Moms",
    taxIdLabel: "Momsregistreringsnummer",
    defaultTaxRate: 25,
  },
  {
    code: "NO",
    name: "Norway",
    flag: "🇳🇴",
    phoneCode: "+47",
    phoneLength: 8,
    currencyCode: "NOK",
    currencySymbol: "kr",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Europe/Oslo",
    dateFormat: "DD.MM.YYYY",
    taxName: "MVA",
    taxIdLabel: "Organisasjonsnummer MVA",
    defaultTaxRate: 25,
  },
  {
    code: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    phoneCode: "+45",
    phoneLength: 8,
    currencyCode: "DKK",
    currencySymbol: "kr.",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Copenhagen",
    dateFormat: "DD-MM-YYYY",
    taxName: "Moms",
    taxIdLabel: "CVR-nummer",
    defaultTaxRate: 25,
  },
  {
    code: "FI",
    name: "Finland",
    flag: "🇫🇮",
    phoneCode: "+358",
    phoneLength: [9, 10],
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Helsinki",
    dateFormat: "DD.MM.YYYY",
    taxName: "ALV",
    taxIdLabel: "ALV-numero / Y-tunnus",
    defaultTaxRate: 25.5,
  },
  {
    code: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    phoneCode: "+353",
    phoneLength: 9,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Europe/Dublin",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "VAT Number",
    defaultTaxRate: 23,
  },
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    phoneCode: "+351",
    phoneLength: 9,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Lisbon",
    dateFormat: "DD/MM/YYYY",
    taxName: "IVA",
    taxIdLabel: "NIF (Número de Identificação Fiscal)",
    defaultTaxRate: 23,
  },
  {
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    phoneCode: "+48",
    phoneLength: 9,
    currencyCode: "PLN",
    currencySymbol: "zł",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Warsaw",
    dateFormat: "DD.MM.YYYY",
    taxName: "VAT",
    taxIdLabel: "NIP (Numer Identyfikacji Podatkowej)",
    defaultTaxRate: 23,
  },
  {
    code: "TR",
    name: "Turkey",
    flag: "🇹🇷",
    phoneCode: "+90",
    phoneLength: 10,
    currencyCode: "TRY",
    currencySymbol: "₺",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Europe/Istanbul",
    dateFormat: "DD.MM.YYYY",
    taxName: "KDV",
    taxIdLabel: "Vergi Kimlik Numarası (VKN)",
    defaultTaxRate: 20,
  },
  {
    code: "GR",
    name: "Greece",
    flag: "🇬🇷",
    phoneCode: "+30",
    phoneLength: 10,
    currencyCode: "EUR",
    currencySymbol: "€",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Athens",
    dateFormat: "DD/MM/YYYY",
    taxName: "FPA",
    taxIdLabel: "AFM (Αριθμός Φορολογικού Μητρώου)",
    defaultTaxRate: 24,
  },
  {
    code: "CZ",
    name: "Czech Republic",
    flag: "🇨🇿",
    phoneCode: "+420",
    phoneLength: 9,
    currencyCode: "CZK",
    currencySymbol: "Kč",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Prague",
    dateFormat: "DD.MM.YYYY",
    taxName: "DPH",
    taxIdLabel: "DIČ (Daňové identifikační číslo)",
    defaultTaxRate: 21,
  },
  {
    code: "HU",
    name: "Hungary",
    flag: "🇭🇺",
    phoneCode: "+36",
    phoneLength: 9,
    currencyCode: "HUF",
    currencySymbol: "Ft",
    currencyPosition: "suffix",
    decimalDigits: 0,
    timeZone: "Europe/Budapest",
    dateFormat: "YYYY.MM.DD",
    taxName: "ÁFA",
    taxIdLabel: "Adószám",
    defaultTaxRate: 27,
  },
  {
    code: "RO",
    name: "Romania",
    flag: "🇷🇴",
    phoneCode: "+40",
    phoneLength: 10,
    currencyCode: "RON",
    currencySymbol: "lei",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Bucharest",
    dateFormat: "DD.MM.YYYY",
    taxName: "TVA",
    taxIdLabel: "CIF / CUI",
    defaultTaxRate: 19,
  },
  {
    code: "RU",
    name: "Russia",
    flag: "🇷🇺",
    phoneCode: "+7",
    phoneLength: 10,
    currencyCode: "RUB",
    currencySymbol: "₽",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Moscow",
    dateFormat: "DD.MM.YYYY",
    taxName: "NDS",
    taxIdLabel: "ИНН (INN)",
    defaultTaxRate: 20,
  },
  {
    code: "UA",
    name: "Ukraine",
    flag: "🇺🇦",
    phoneCode: "+380",
    phoneLength: 9,
    currencyCode: "UAH",
    currencySymbol: "₴",
    currencyPosition: "suffix",
    decimalDigits: 2,
    timeZone: "Europe/Kyiv",
    dateFormat: "DD.MM.YYYY",
    taxName: "PDV",
    taxIdLabel: "ІПН (IPN)",
    defaultTaxRate: 20,
  },

  // --- Middle East & Gulf (GCC) ---
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    phoneCode: "+971",
    phoneLength: 9,
    currencyCode: "AED",
    currencySymbol: "AED",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Dubai",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "TRN (Tax Registration Number)",
    defaultTaxRate: 5,
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    phoneCode: "+966",
    phoneLength: 9,
    currencyCode: "SAR",
    currencySymbol: "SAR",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Riyadh",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "ZATCA VAT Account Number",
    defaultTaxRate: 15,
  },
  {
    code: "QA",
    name: "Qatar",
    flag: "🇶🇦",
    phoneCode: "+974",
    phoneLength: 8,
    currencyCode: "QAR",
    currencySymbol: "QAR",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Qatar",
    dateFormat: "DD/MM/YYYY",
    taxName: "Tax ID",
    taxIdLabel: "TIN (Tax Identification Number)",
    defaultTaxRate: 0,
  },
  {
    code: "KW",
    name: "Kuwait",
    flag: "🇰🇼",
    phoneCode: "+965",
    phoneLength: 8,
    currencyCode: "KWD",
    currencySymbol: "KD",
    currencyPosition: "prefix",
    decimalDigits: 3,
    timeZone: "Asia/Kuwait",
    dateFormat: "DD/MM/YYYY",
    taxName: "Tax ID",
    taxIdLabel: "Commercial Registration (CR)",
    defaultTaxRate: 0,
  },
  {
    code: "BH",
    name: "Bahrain",
    flag: "🇧🇭",
    phoneCode: "+973",
    phoneLength: 8,
    currencyCode: "BHD",
    currencySymbol: "BD",
    currencyPosition: "prefix",
    decimalDigits: 3,
    timeZone: "Asia/Bahrain",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "NBR VAT Account Number",
    defaultTaxRate: 10,
  },
  {
    code: "OM",
    name: "Oman",
    flag: "🇴🇲",
    phoneCode: "+968",
    phoneLength: 8,
    currencyCode: "OMR",
    currencySymbol: "OMR",
    currencyPosition: "prefix",
    decimalDigits: 3,
    timeZone: "Asia/Muscat",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "OTA VAT Identification Number",
    defaultTaxRate: 5,
  },
  {
    code: "JO",
    name: "Jordan",
    flag: "🇯🇴",
    phoneCode: "+962",
    phoneLength: 9,
    currencyCode: "JOD",
    currencySymbol: "JD",
    currencyPosition: "prefix",
    decimalDigits: 3,
    timeZone: "Asia/Amman",
    dateFormat: "DD/MM/YYYY",
    taxName: "GST / Sales Tax",
    taxIdLabel: "National Tax Number",
    defaultTaxRate: 16,
  },
  {
    code: "IL",
    name: "Israel",
    flag: "🇮🇱",
    phoneCode: "+972",
    phoneLength: 9,
    currencyCode: "ILS",
    currencySymbol: "₪",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Jerusalem",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT (Ma'am)",
    taxIdLabel: "Authorized Dealer / Osek Murshe",
    defaultTaxRate: 17,
  },
  {
    code: "EG",
    name: "Egypt",
    flag: "🇪🇬",
    phoneCode: "+20",
    phoneLength: 10,
    currencyCode: "EGP",
    currencySymbol: "E£",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Africa/Cairo",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "ETA Tax Card Number",
    defaultTaxRate: 14,
  },

  // --- South Asia ---
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    phoneCode: "+91",
    phoneLength: 10,
    currencyCode: "INR",
    currencySymbol: "₹",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Kolkata",
    dateFormat: "DD/MM/YYYY",
    taxName: "GST",
    taxIdLabel: "GSTIN (Goods and Services Tax ID)",
    defaultTaxRate: 18,
  },
  {
    code: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
    phoneCode: "+880",
    phoneLength: 10,
    currencyCode: "BDT",
    currencySymbol: "৳",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Dhaka",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "BIN (Business Identification Number)",
    defaultTaxRate: 5,
  },
  {
    code: "PK",
    name: "Pakistan",
    flag: "🇵🇰",
    phoneCode: "+92",
    phoneLength: 10,
    currencyCode: "PKR",
    currencySymbol: "Rs",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Karachi",
    dateFormat: "DD/MM/YYYY",
    taxName: "GST / Sales Tax",
    taxIdLabel: "NTN / STRN Number",
    defaultTaxRate: 18,
  },
  {
    code: "LK",
    name: "Sri Lanka",
    flag: "🇱🇰",
    phoneCode: "+94",
    phoneLength: 9,
    currencyCode: "LKR",
    currencySymbol: "Rs",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Colombo",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "TIN / VAT Registration No.",
    defaultTaxRate: 18,
  },
  {
    code: "NP",
    name: "Nepal",
    flag: "🇳🇵",
    phoneCode: "+977",
    phoneLength: 10,
    currencyCode: "NPR",
    currencySymbol: "Rs",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Kathmandu",
    dateFormat: "YYYY-MM-DD",
    taxName: "VAT",
    taxIdLabel: "PAN (Permanent Account Number)",
    defaultTaxRate: 13,
  },

  // --- East & Southeast Asia ---
  {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    phoneCode: "+65",
    phoneLength: 8,
    currencyCode: "SGD",
    currencySymbol: "S$",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Singapore",
    dateFormat: "DD/MM/YYYY",
    taxName: "GST",
    taxIdLabel: "UEN / GST Reg No.",
    defaultTaxRate: 9,
  },
  {
    code: "MY",
    name: "Malaysia",
    flag: "🇲🇾",
    phoneCode: "+60",
    phoneLength: [9, 10],
    currencyCode: "MYR",
    currencySymbol: "RM",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Kuala_Lumpur",
    dateFormat: "DD/MM/YYYY",
    taxName: "SST",
    taxIdLabel: "SST Registration Number",
    defaultTaxRate: 8,
  },
  {
    code: "ID",
    name: "Indonesia",
    flag: "🇮🇩",
    phoneCode: "+62",
    phoneLength: [10, 11, 12],
    currencyCode: "IDR",
    currencySymbol: "Rp",
    currencyPosition: "prefix",
    decimalDigits: 0,
    timeZone: "Asia/Jakarta",
    dateFormat: "DD/MM/YYYY",
    taxName: "PPN (VAT)",
    taxIdLabel: "NPWP (Nomor Pokok Wajib Pajak)",
    defaultTaxRate: 11,
  },
  {
    code: "TH",
    name: "Thailand",
    flag: "🇹🇭",
    phoneCode: "+66",
    phoneLength: 9,
    currencyCode: "THB",
    currencySymbol: "฿",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Bangkok",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "Tax Identification Number (TIN)",
    defaultTaxRate: 7,
  },
  {
    code: "VN",
    name: "Vietnam",
    flag: "🇻🇳",
    phoneCode: "+84",
    phoneLength: 9,
    currencyCode: "VND",
    currencySymbol: "₫",
    currencyPosition: "suffix",
    decimalDigits: 0,
    timeZone: "Asia/Ho_Chi_Minh",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT (GTGT)",
    taxIdLabel: "Mã số thuế (MST)",
    defaultTaxRate: 10,
  },
  {
    code: "PH",
    name: "Philippines",
    flag: "🇵🇭",
    phoneCode: "+63",
    phoneLength: 10,
    currencyCode: "PHP",
    currencySymbol: "₱",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Manila",
    dateFormat: "MM/DD/YYYY",
    taxName: "VAT",
    taxIdLabel: "BIR TIN (Taxpayer ID)",
    defaultTaxRate: 12,
  },
  {
    code: "JP",
    name: "Japan",
    flag: "🇯🇵",
    phoneCode: "+81",
    phoneLength: 10,
    currencyCode: "JPY",
    currencySymbol: "¥",
    currencyPosition: "prefix",
    decimalDigits: 0,
    timeZone: "Asia/Tokyo",
    dateFormat: "YYYY/MM/DD",
    taxName: "Consumption Tax (JCT)",
    taxIdLabel: "Qualified Invoice Business Reg No.",
    defaultTaxRate: 10,
  },
  {
    code: "KR",
    name: "South Korea",
    flag: "🇰🇷",
    phoneCode: "+82",
    phoneLength: 10,
    currencyCode: "KRW",
    currencySymbol: "₩",
    currencyPosition: "prefix",
    decimalDigits: 0,
    timeZone: "Asia/Seoul",
    dateFormat: "YYYY.MM.DD",
    taxName: "VAT",
    taxIdLabel: "Business Registration Number (BRN)",
    defaultTaxRate: 10,
  },
  {
    code: "CN",
    name: "China",
    flag: "🇨🇳",
    phoneCode: "+86",
    phoneLength: 11,
    currencyCode: "CNY",
    currencySymbol: "¥",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Shanghai",
    dateFormat: "YYYY-MM-DD",
    taxName: "VAT",
    taxIdLabel: "Unified Social Credit Code (USCC)",
    defaultTaxRate: 13,
  },
  {
    code: "HK",
    name: "Hong Kong",
    flag: "🇭🇰",
    phoneCode: "+852",
    phoneLength: 8,
    currencyCode: "HKD",
    currencySymbol: "HK$",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Asia/Hong_Kong",
    dateFormat: "DD/MM/YYYY",
    taxName: "Tax ID",
    taxIdLabel: "Business Registration (BRN)",
    defaultTaxRate: 0,
  },
  {
    code: "TW",
    name: "Taiwan",
    flag: "🇹🇼",
    phoneCode: "+886",
    phoneLength: 9,
    currencyCode: "TWD",
    currencySymbol: "NT$",
    currencyPosition: "prefix",
    decimalDigits: 0,
    timeZone: "Asia/Taipei",
    dateFormat: "YYYY/MM/DD",
    taxName: "VAT / GUI",
    taxIdLabel: "Unified Business Number (UBN)",
    defaultTaxRate: 5,
  },

  // --- Oceania ---
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    phoneCode: "+61",
    phoneLength: 9,
    currencyCode: "AUD",
    currencySymbol: "A$",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Australia/Sydney",
    dateFormat: "DD/MM/YYYY",
    taxName: "GST",
    taxIdLabel: "ABN (Australian Business Number)",
    defaultTaxRate: 10,
  },
  {
    code: "NZ",
    name: "New Zealand",
    flag: "🇳🇿",
    phoneCode: "+64",
    phoneLength: [8, 9],
    currencyCode: "NZD",
    currencySymbol: "NZ$",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Pacific/Auckland",
    dateFormat: "DD/MM/YYYY",
    taxName: "GST",
    taxIdLabel: "NZBN / GST Number",
    defaultTaxRate: 15,
  },

  // --- Latin America ---
  {
    code: "BR",
    name: "Brazil",
    flag: "🇧🇷",
    phoneCode: "+55",
    phoneLength: 11,
    currencyCode: "BRL",
    currencySymbol: "R$",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "America/Sao_Paulo",
    dateFormat: "DD/MM/YYYY",
    taxName: "ICMS / ISS / PIS",
    taxIdLabel: "CNPJ / CPF",
    defaultTaxRate: 17,
  },
  {
    code: "AR",
    name: "Argentina",
    flag: "🇦🇷",
    phoneCode: "+54",
    phoneLength: 10,
    currencyCode: "ARS",
    currencySymbol: "$",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "America/Argentina/Buenos_Aires",
    dateFormat: "DD/MM/YYYY",
    taxName: "IVA",
    taxIdLabel: "CUIT / CUIL",
    defaultTaxRate: 21,
  },
  {
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    phoneCode: "+56",
    phoneLength: 9,
    currencyCode: "CLP",
    currencySymbol: "$",
    currencyPosition: "prefix",
    decimalDigits: 0,
    timeZone: "America/Santiago",
    dateFormat: "DD-MM-YYYY",
    taxName: "IVA",
    taxIdLabel: "RUT (Rol Único Tributario)",
    defaultTaxRate: 19,
  },
  {
    code: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    phoneCode: "+57",
    phoneLength: 10,
    currencyCode: "COP",
    currencySymbol: "$",
    currencyPosition: "prefix",
    decimalDigits: 0,
    timeZone: "America/Bogota",
    dateFormat: "DD/MM/YYYY",
    taxName: "IVA",
    taxIdLabel: "NIT (Número de Identificación Tributaria)",
    defaultTaxRate: 19,
  },
  {
    code: "PE",
    name: "Peru",
    flag: "🇵🇪",
    phoneCode: "+51",
    phoneLength: 9,
    currencyCode: "PEN",
    currencySymbol: "S/",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "America/Lima",
    dateFormat: "DD/MM/YYYY",
    taxName: "IGV (IVA)",
    taxIdLabel: "RUC (Registro Único de Contribuyentes)",
    defaultTaxRate: 18,
  },

  // --- Africa ---
  {
    code: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    phoneCode: "+27",
    phoneLength: 9,
    currencyCode: "ZAR",
    currencySymbol: "R",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Africa/Johannesburg",
    dateFormat: "YYYY/MM/DD",
    taxName: "VAT",
    taxIdLabel: "SARS VAT Registration Number",
    defaultTaxRate: 15,
  },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    phoneCode: "+234",
    phoneLength: 10,
    currencyCode: "NGN",
    currencySymbol: "₦",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Africa/Lagos",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "FIRS TIN (Tax Identification Number)",
    defaultTaxRate: 7.5,
  },
  {
    code: "KE",
    name: "Kenya",
    flag: "🇰🇪",
    phoneCode: "+254",
    phoneLength: 9,
    currencyCode: "KES",
    currencySymbol: "KSh",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Africa/Nairobi",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "KRA PIN",
    defaultTaxRate: 16,
  },
  {
    code: "GH",
    name: "Ghana",
    flag: "🇬🇭",
    phoneCode: "+233",
    phoneLength: 9,
    currencyCode: "GHS",
    currencySymbol: "GH₵",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Africa/Accra",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT / NHIL",
    taxIdLabel: "GRA TIN",
    defaultTaxRate: 15,
  },
  {
    code: "MA",
    name: "Morocco",
    flag: "🇲🇦",
    phoneCode: "+212",
    phoneLength: 9,
    currencyCode: "MAD",
    currencySymbol: "DH",
    currencyPosition: "prefix",
    decimalDigits: 2,
    timeZone: "Africa/Casablanca",
    dateFormat: "DD/MM/YYYY",
    taxName: "TVA",
    taxIdLabel: "ICE / Identifiant Fiscal (IF)",
    defaultTaxRate: 20,
  },
  {
    code: "TZ",
    name: "Tanzania",
    flag: "🇹🇿",
    phoneCode: "+255",
    phoneLength: 9,
    currencyCode: "TZS",
    currencySymbol: "TSh",
    currencyPosition: "prefix",
    decimalDigits: 0,
    timeZone: "Africa/Dar_es_Salaam",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "TRA TIN / VRN",
    defaultTaxRate: 18,
  },
  {
    code: "UG",
    name: "Uganda",
    flag: "🇺🇬",
    phoneCode: "+256",
    phoneLength: 9,
    currencyCode: "UGX",
    currencySymbol: "USh",
    currencyPosition: "prefix",
    decimalDigits: 0,
    timeZone: "Africa/Kampala",
    dateFormat: "DD/MM/YYYY",
    taxName: "VAT",
    taxIdLabel: "URA TIN",
    defaultTaxRate: 18,
  },
];

/**
 * Quick lookup index for countries by code or calling code.
 */
export function getCountryByIso(isoCode: string): CountryInfo | undefined {
  if (!isoCode) return undefined;
  return COUNTRIES.find((c) => c.code.toUpperCase() === isoCode.toUpperCase());
}

export function getCountryByPhoneCode(phoneCode: string): CountryInfo | undefined {
  if (!phoneCode) return undefined;
  const clean = phoneCode.startsWith("+") ? phoneCode : `+${phoneCode}`;
  return COUNTRIES.find((c) => c.phoneCode === clean);
}

export function getCountryByName(name: string): CountryInfo | undefined {
  if (!name) return undefined;
  const target = name.toLowerCase().trim();
  return COUNTRIES.find((c) => c.name.toLowerCase() === target || c.code.toLowerCase() === target);
}

export function getCountryOptionList() {
  return COUNTRIES.map((c) => ({
    value: c.code,
    label: `${c.flag} ${c.name} (${c.phoneCode})`,
    phoneCode: c.phoneCode,
    currencyCode: c.currencyCode,
    currencySymbol: c.currencySymbol,
    timeZone: c.timeZone,
    taxName: c.taxName,
    taxIdLabel: c.taxIdLabel,
    defaultTaxRate: c.defaultTaxRate,
  }));
}
