import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from "react";

export type LanguageCode = "en" | "bn" | "ar" | "hi" | "zh";

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeName: string;
  flag: string;
  dir: "ltr" | "rtl";
}

export const LANGUAGES: LanguageOption[] = [
  { code: "en", label: "English", nativeName: "English", flag: "🇺🇸", dir: "ltr" },
  { code: "bn", label: "Bengali", nativeName: "বাংলা", flag: "🇧🇩", dir: "ltr" },
  { code: "ar", label: "Arabic", nativeName: "العربية", flag: "🇸🇦", dir: "rtl" },
  { code: "hi", label: "Hindi", nativeName: "हिंदी", flag: "🇮🇳", dir: "ltr" },
  { code: "zh", label: "Chinese", nativeName: "中文", flag: "🇨🇳", dir: "ltr" },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    pos: "POS Terminal",
    products: "Products",
    categories: "Categories",
    customers: "Customers",
    suppliers: "Suppliers",
    sales: "Sales History",
    settings: "Settings",
    search: "Search...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add New",
    status: "Status",
    price: "Price",
    checkout: "Checkout",
    welcome: "Welcome back",
    trialDaysLeft: "days left in trial",
    emailVerificationRequired: "Email Verification Required",
    verifyEmail: "Verify Email",
    otpSentNotice: "Enter 6-digit OTP code sent to your email.",
    language: "Language",
    countryCode: "Country Code",
    timezone: "Timezone",
    dateFormat: "Date Format",
    manageCatalog: "Manage your full SKU catalog, pricing, and stock thresholds.",
    addProduct: "Add Product",
    appointments: "Appointments",
    tables: "Tables",
    kitchen: "Kitchen",
    searchProducts: "Search by name, SKU, or barcode...",
    noProductsFound: "No products found",
    adjustSearch: "Try adjusting your search.",
    noProductsYet: "You haven't added any products yet.",
    product: "Product",
    sku: "SKU",
    category: "Category",
    manageCustomers: "Manage customer relationships, loyalty, and ledgers.",
    addCustomer: "Add Customer",
    searchCustomers: "Search by name, email, or phone...",
    noCustomersFound: "No customers found",
    noCustomersYet: "You haven't added any customers yet.",
    customer: "Customer",
    contact: "Contact",
    visits: "Visits",
    lifetime: "Lifetime",
    points: "Points",
    credit: "Credit",
    wallet: "Wallet",
    tier: "Tier",
    actions: "Actions",
    manageSuppliers: "Manage vendor relationships, purchase history, and outstanding balances.",
    addSupplier: "Add Supplier",
    searchSuppliers: "Search by name, contact, or email...",
    noSuppliersFound: "No suppliers found",
    noSuppliersYet: "You haven't added any suppliers yet.",
    due: "due",
    settled: "Settled",
    itemsSupplied: "Items supplied",
    manageSales: "Every transaction across all your registers.",
    searchSales: "Search by invoice or customer...",
    noSalesFound: "No sales found",
    noSalesYet: "No transactions have been recorded yet.",
    invoice: "Invoice",
    date: "Date",
    payment: "Payment",
    sync: "Sync",
    total: "Total",
    salesReturns: "Sales Returns",
    manageReturns: "Refunds and exchanges issued to customers.",
    processReturn: "Process Return",
    searchReturns: "Search by ref or customer...",
    noReturnsFound: "No returns found",
    noReturnsYet: "No sales returns have been recorded yet.",
    ref: "Ref",
    reason: "Reason",
    refund: "Refund",
    purchases: "Purchases",
    managePurchases: "Inbound inventory from suppliers and purchase orders.",
    newPurchase: "New Purchase",
    searchPurchases: "Search by PO or supplier...",
    noPurchasesFound: "No purchases found",
    noPurchasesYet: "No purchase orders have been created yet.",
    po: "PO",
    supplier: "Supplier",
    expenses: "Expenses",
    manageExpenses: "Track operating costs across all categories.",
    totalExpenses: "Total Expenses",
    largestCategory: "Largest Category",
    pending: "Pending",
    addExpense: "Add Expense",
    searchExpenses: "Search by category or description...",
    noExpensesFound: "No expenses found",
    noExpensesYet: "No expenses have been recorded yet.",
    description: "Description",
    amount: "Amount",
    profile: "Profile",
    logout: "Sign out",
    closeRegister: "Close Register",
    notifications: "Notifications",
    help: "Help center",
    storeInfo: "Store Information",
    storeName: "Store name",
    taxId: "Tax ID",
    address: "Address",
    phone: "Phone",
    email: "Email",
    currency: "Currency",
    billing: "Billing",
    appearance: "Appearance",
    receipts: "Receipts",
    paymentMethods: "Payment Methods",
    taxes: "Taxes",
    users: "Users & Roles",
    active: "Active",
    inactive: "Inactive",
    newSale: "New Sale",
    overview: "Overview",
    catalog: "Catalog",
    brands: "Brands",
    units: "Units",
    stock: "Stock",
    inventory: "Inventory",
    adjustments: "Adjustments",
    transfers: "Transfers",
    stockHistory: "Stock History",
    tradeB2B: "Trade & B2B",
    purchaseReturns: "Purchase Returns",
    salesInvoices: "Sales Invoices",
    quotations: "Quotations",
    deliveryChallans: "Delivery Challans",
    people: "People",
    employees: "Employees",
    finance: "Finance & Accounts",
    accounts: "Chart of Accounts",
    accounting_reports: "Accounting Reports",
    reports: "Financial Reports",
    services: "Services & Verticals",
    repairs: "Repair Job Sheets",
    subscriptions: "Subscriptions",
    rentals: "Equipment Rentals",
    marketing: "Marketing",
    coupons: "Coupons",
    giftCards: "Gift Cards",
    loyalty: "Loyalty",
    promotions: "Promotions",
    system: "System",
    superAdmin: "Super Admin SaaS",
    clientPortal: "Client Portal",
    activityLog: "Activity Log",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    pos: "পজ টার্মিনাল",
    products: "পণ্য তালিকা",
    categories: "ক্যাটাগরি",
    customers: "গ্রাহক খাতা",
    suppliers: "সরবরাহকারী",
    sales: "বিক্রয় ইতিহাস",
    settings: "সেটিংস",
    search: "অনুসন্ধান করুন...",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল",
    delete: "মুছুন",
    edit: "সম্পাদনা",
    add: "নতুন যুক্ত করুন",
    status: "স্ট্যাটাস",
    price: "মূল্য",
    checkout: "চেকআউট",
    welcome: "স্বাগতম",
    trialDaysLeft: "দিন ট্রায়াল বাকী",
    emailVerificationRequired: "ইমেইল ভেরিফিকেশন প্রয়োজন",
    verifyEmail: "ইমেইল ভেরিফাই করুন",
    otpSentNotice: "আপনার ইমেইলে পাঠানো ৬-সংখ্যার OTP কোডটি লিখুন।",
    language: "ভাষা",
    countryCode: "কান্ট্রি কোড",
    timezone: "টাইমজোন",
    dateFormat: "তারিখ ফরম্যাট",
    manageCatalog: "আপনার সম্পূর্ণ এসকেইউ ক্যাটালগ, প্রাইসিং এবং স্টক পরিচালনা করুন।",
    addProduct: "পণ্য যোগ করুন",
    searchProducts: "নাম, এসকেইউ অথবা বারকোড দিয়ে খুঁজুন...",
    noProductsFound: "কোনো পণ্য পাওয়া যায়নি",
    adjustSearch: "আপনার অনুসন্ধান পরিবর্তন করে দেখুন।",
    noProductsYet: "আপনি এখনও কোনো পণ্য যোগ করেননি।",
    product: "পণ্য",
    sku: "এসকেইউ",
    category: "ক্যাটাগরি",
    manageCustomers: "গ্রাহকদের সম্পর্ক, লয়্যালটি এবং লেজার পরিচালনা করুন।",
    addCustomer: "গ্রাহক যোগ করুন",
    searchCustomers: "নাম, ইমেইল অথবা ফোন নম্বর দিয়ে খুঁজুন...",
    noCustomersFound: "কোনো গ্রাহক পাওয়া যায়নি",
    noCustomersYet: "আপনি এখনও কোনো গ্রাহক যোগ করেননি।",
    customer: "গ্রাহক",
    contact: "যোগাযোগ",
    visits: "ভিজিট",
    lifetime: "আজীবন",
    points: "পয়েন্ট",
    credit: "বাকি",
    wallet: "ওয়ালেট",
    tier: "টিয়ার",
    actions: "অ্যাকশন",
    manageSuppliers: "ভেন্ডর সম্পর্ক, ক্রয়ের ইতিহাস এবং বকেয়া ব্যালেন্স পরিচালনা করুন।",
    addSupplier: "সাপ্লায়ার যোগ করুন",
    searchSuppliers: "নাম, যোগাযোগ অথবা ইমেইল দিয়ে খুঁজুন...",
    noSuppliersFound: "কোনো সাপ্লায়ার পাওয়া যায়নি",
    noSuppliersYet: "আপনি এখনও কোনো সাপ্লায়ার যোগ করেননি।",
    due: "বাকি",
    settled: "পরিশোধিত",
    itemsSupplied: "সরবরাহকৃত আইটেম",
    manageSales: "আপনার সকল রেজিস্টারের প্রতিটি লেনদেন।",
    searchSales: "ইনভয়েস বা গ্রাহক দ্বারা খুঁজুন...",
    noSalesFound: "কোনো বিক্রয় পাওয়া যায়নি",
    noSalesYet: "এখনো কোনো লেনদেন রেকর্ড করা হয়নি।",
    invoice: "ইনভয়েস",
    date: "তারিখ",
    payment: "পেমেন্ট",
    sync: "সিঙ্ক",
    total: "মোট",
    salesReturns: "বিক্রয় ফেরত",
    manageReturns: "গ্রাহকদের দেওয়া রিফান্ড এবং পরিবর্তনসমূহ।",
    processReturn: "রিটার্ন প্রক্রিয়া করুন",
    searchReturns: "রেফারেন্স বা গ্রাহক দ্বারা খুঁজুন...",
    noReturnsFound: "কোনো রিটার্ন পাওয়া যায়নি",
    noReturnsYet: "এখনো কোনো বিক্রয় ফেরত রেকর্ড করা হয়নি।",
    ref: "রেফ",
    reason: "কারণ",
    refund: "রিফান্ড",
    purchases: "ক্রয়",
    managePurchases: "সাপ্লায়ার এবং পারচেজ অর্ডার থেকে আগত ইনভেন্টরি।",
    newPurchase: "নতুন ক্রয়",
    searchPurchases: "পিও (PO) বা সাপ্লায়ার দ্বারা খুঁজুন...",
    noPurchasesFound: "কোনো ক্রয় পাওয়া যায়নি",
    noPurchasesYet: "এখনো কোনো পারচেজ অর্ডার তৈরি করা হয়নি।",
    po: "পিও (PO)",
    supplier: "সাপ্লায়ার",
    expenses: "খরচ",
    manageExpenses: "সব ক্যাটাগরি জুড়ে অপারেটিং খরচ ট্র্যাক করুন।",
    totalExpenses: "মোট খরচ",
    largestCategory: "সবচেয়ে বড় ক্যাটাগরি",
    pending: "অমীমাংসিত",
    addExpense: "খরচ যোগ করুন",
    searchExpenses: "ক্যাটাগরি বা বিবরণ দ্বারা খুঁজুন...",
    noExpensesFound: "কোনো খরচ পাওয়া যায়নি",
    noExpensesYet: "এখনো কোনো খরচ রেকর্ড করা হয়নি।",
    description: "বিবরণ",
    amount: "পরিমাণ",
    profile: "প্রোফাইল",
    logout: "লগ আউট",
    closeRegister: "রেজিস্টার বন্ধ করুন",
    notifications: "নোটিফিকেশন",
    help: "সাহায্য কেন্দ্র",
    storeInfo: "স্টোর তথ্য",
    storeName: "স্টোরের নাম",
    taxId: "ট্যাক্স আইডি",
    address: "ঠিকানা",
    phone: "ফোন নম্বর",
    email: "ইমেইল",
    currency: "মুদ্রা",
    billing: "বিলিং",
    appearance: "চেহারা",
    receipts: "রসিদ",
    paymentMethods: "পেমেন্ট পদ্ধতি",
    taxes: "ট্যাক্স",
    users: "ইউজার এবং রোল",
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    newSale: "নতুন বিক্রয়",
    overview: "ওভারভিউ",
    catalog: "ক্যাটালগ",
    brands: "ব্র্যান্ড",
    units: "ইউনিট",
    stock: "স্টক",
    inventory: "ইনভেন্টরি",
    adjustments: "অ্যাডজাস্টমেন্ট",
    transfers: "ট্রান্সফার",
    stockHistory: "স্টক হিস্ট্রি",
    tradeB2B: "ট্রেড ও বিটুবি",
    purchaseReturns: "ক্রয় ফেরত",
    salesInvoices: "বিক্রয় ইনভয়েস",
    quotations: "কোটেশন",
    deliveryChallans: "ডেলিভারি চালান",
    people: "লোকজন",
    employees: "কর্মচারী",
    finance: "অর্থ ও হিসাব",
    accounts: "হিসাবের তালিকা",
    reports: "আর্থিক প্রতিবেদন",
    services: "পরিষেবা",
    repairs: "মেরামত জব শিট",
    subscriptions: "সাবস্ক্রিপশন",
    rentals: "ভাড়া",
    marketing: "মার্কেটিং",
    coupons: "কুপন",
    giftCards: "গিফট কার্ড",
    loyalty: "লয়্যালটি",
    promotions: "প্রোমোশন",
    system: "সিستم",
    superAdmin: "সুপার অ্যাডমিন",
    clientPortal: "ক্লাইন্ট পোর্টাল",
    activityLog: "অ্যাক্টিভিটি লগ",
  },
  ar: {
    dashboard: "لوحة التحكم",
    pos: "نقطة البيع",
    products: "المنتجات",
    categories: "الفئات",
    customers: "العملاء",
    suppliers: "الموردون",
    sales: "المبيعات",
    settings: "الإعدادات",
    search: "بحث...",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة جديد",
    status: "الحالة",
    price: "السعر",
    checkout: "الدفع والتسديد",
    welcome: "مرحباً بعودتك",
    trialDaysLeft: "أيام متبقية في التجربة",
    emailVerificationRequired: "مطلوب تأكيد البريد الإلكتروني",
    verifyEmail: "تأكيد البريد",
    otpSentNotice: "أدخل رمز التحقق المكون من 6 أرقام المرسل إلى بريدك.",
    language: "اللغة",
    countryCode: "رمز الدولة",
    timezone: "المنطقة الزمنية",
    dateFormat: "تنسيق التاريخ",
    manageCatalog: "إدارة الكتالوج الكامل والتسعير وحدود المخزون.",
    addProduct: "إضافة منتج",
    searchProducts: "ابحث بالاسم، أو الباركود...",
    noProductsFound: "لم يتم العثور على منتجات",
    adjustSearch: "حاول تعديل البحث.",
    noProductsYet: "لم تقم بإضافة أي منتجات بعد.",
    product: "المنتج",
    sku: "SKU",
    category: "الفئة",
    manageCustomers: "إدارة علاقات العملاء والولاء والدفاتر.",
    addCustomer: "إضافة عميل",
    searchCustomers: "البحث بالاسم والبريد الإلكتروني أو الهاتف...",
    noCustomersFound: "لم يتم العثور على عملاء",
    noCustomersYet: "لم تقم بإضافة أي عملاء بعد.",
    customer: "العميل",
    contact: "اتصال",
    visits: "زيارات",
    lifetime: "حياة",
    points: "نقاط",
    credit: "رصيد",
    wallet: "محفظة",
    tier: "مستوى",
    actions: "إجراءات",
    manageSuppliers: "إدارة علاقات الموردين وتاريخ الشراء والأرصدة المستحقة.",
    addSupplier: "إضافة مورد",
    searchSuppliers: "البحث بالاسم والاتصال أو البريد الإلكتروني...",
    noSuppliersFound: "لم يتم العثور على موردين",
    noSuppliersYet: "لم تقم بإضافة أي موردين بعد.",
    due: "مستحق",
    settled: "تمت التسوية",
    itemsSupplied: "العناصر الموردة",
    manageSales: "كل معاملة عبر جميع السجلات الخاصة بك.",
    searchSales: "البحث عن طريق الفاتورة أو العميل...",
    noSalesFound: "لم يتم العثور على مبيعات",
    noSalesYet: "لم يتم تسجيل أي معاملات بعد.",
    invoice: "الفاتورة",
    date: "التاريخ",
    payment: "الدفع",
    sync: "مزامنة",
    total: "الإجمالي",
    salesReturns: "عائدات المبيعات",
    manageReturns: "المبالغ المستردة والاستبدالات الصادرة للعملاء.",
    processReturn: "معالجة الإرجاع",
    searchReturns: "البحث حسب المرجع أو العميل...",
    noReturnsFound: "لم يتم العثور على مرتجعات",
    noReturnsYet: "لم يتم تسجيل أي عائدات مبيعات بعد.",
    ref: "مرجع",
    reason: "السبب",
    refund: "استرداد",
    purchases: "مشتريات",
    managePurchases: "المخزون الوارد من الموردين وأوامر الشراء.",
    newPurchase: "شراء جديد",
    searchPurchases: "البحث عن طريق أمر الشراء أو المورد...",
    noPurchasesFound: "لم يتم العثور على مشتريات",
    noPurchasesYet: "لم يتم إنشاء أي أوامر شراء بعد.",
    po: "أمر شراء",
    supplier: "مورد",
    expenses: "المصروفات",
    manageExpenses: "تتبع تكاليف التشغيل عبر جميع الفئات.",
    totalExpenses: "إجمالي المصروفات",
    largestCategory: "أكبر فئة",
    pending: "قيد الانتظار",
    addExpense: "إضافة مصروف",
    searchExpenses: "البحث عن طريق الفئة أو الوصف...",
    noExpensesFound: "لم يتم العثور على مصروفات",
    noExpensesYet: "لم يتم تسجيل أي مصروفات بعد.",
    description: "الوصف",
    amount: "المبلغ",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    closeRegister: "إغلاق السجل",
    notifications: "الإشعارات",
    help: "مركز المساعدة",
    storeInfo: "معلومات المتجر",
    storeName: "اسم المتجر",
    taxId: "الرقم الضريبي",
    address: "العنوان",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    currency: "العملة",
    billing: "الفواتير",
    appearance: "المظهر",
    receipts: "الإيصالات",
    paymentMethods: "طرق الدفع",
    taxes: "الضرائب",
    users: "المستخدمين والأدوار",
    active: "نشط",
    inactive: "غير نشط",
    newSale: "بيع جديد",
    overview: "نظرة عامة",
    catalog: "فهرس",
    brands: "العلامات التجارية",
    units: "الوحدات",
    stock: "المخزون",
    inventory: "الجرد",
    adjustments: "التعديلات",
    transfers: "التحويلات",
    stockHistory: "سجل المخزون",
    tradeB2B: "التجارة والشركات",
    purchaseReturns: "مرتجعات المشتريات",
    salesInvoices: "فواتير المبيعات",
    quotations: "عروض الأسعار",
    deliveryChallans: "إيصالات التسليم",
    people: "الأشخاص",
    employees: "الموظفون",
    finance: "المالية والحسابات",
    accounts: "دليل الحسابات",
    reports: "التقارير المالية",
    services: "الخدمات",
    repairs: "أوراق عمل الإصلاح",
    subscriptions: "الاشتراكات",
    rentals: "تأجير المعدات",
    marketing: "营销",
    coupons: "الكوبونات",
    giftCards: "بطاقات الهدايا",
    loyalty: "الولاء",
    promotions: "العروض الترويجية",
    system: "النظام",
    superAdmin: "المدير المتميز",
    clientPortal: "بوابة العميل",
    activityLog: "سجل النشاط",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    pos: "पीओएस टर्मिनल",
    products: "उत्पाद",
    categories: "श्रेणियां",
    customers: "ग्राहक खाता",
    suppliers: "आपूर्तिकर्ता",
    sales: "बिक्री इतिहास",
    settings: "सेटिंग्स",
    search: "खोजें...",
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    add: "नया जोड़ें",
    status: "स्थिति",
    price: "मूल्य",
    checkout: "चेकआउट",
    welcome: "स्वागत है",
    trialDaysLeft: "दिन ट्रायल शेष",
    emailVerificationRequired: "ईमेल सत्यापन आवश्यक है",
    verifyEmail: "ईमेल सत्यापित करें",
    otpSentNotice: "अपने ईमेल पर भेजा गया 6-अंकों का ओटीपी दर्ज करें।",
    language: "भाषा",
    countryCode: "कंट्री कोड",
    timezone: "टाइमज़ोन",
    dateFormat: "तारीख प्रारूप",
    manageCatalog: "अपना पूरा SKU कैटलॉग, मूल्य निर्धारण और स्टॉक सीमा प्रबंधित करें।",
    addProduct: "उत्पाद जोड़ें",
    searchProducts: "नाम, SKU या बारकोड से खोजें...",
    noProductsFound: "कोई उत्पाद नहीं मिला",
    adjustSearch: "अपनी खोज को समायोजित करने का प्रयास करें।",
    noProductsYet: "आपने अभी तक कोई उत्पाद नहीं जोड़ा है।",
    product: "उत्पाद",
    sku: "एसकेयू",
    category: "श्रेणी",
    manageCustomers: "ग्राहक संबंध, वफादारी और लेजर प्रबंधित करें।",
    addCustomer: "ग्राहक जोड़ें",
    searchCustomers: "नाम, ईमेल या फोन द्वारा खोजें...",
    noCustomersFound: "कोई ग्राहक नहीं मिला",
    noCustomersYet: "आपने अभी तक कोई ग्राहक नहीं जोड़ा है।",
    customer: "ग्राहक",
    contact: "संपर्क",
    visits: "विज़िट",
    lifetime: "आजीवन",
    points: "पॉइंट्स",
    credit: "क्रेडिट",
    wallet: "बटुआ",
    tier: "श्रेणी",
    actions: "क्रिया",
    manageSuppliers: "विक्रेता संबंध, खरीद इतिहास और बकाया शेष प्रबंधित करें।",
    addSupplier: "आपूर्तिकर्ता जोड़ें",
    searchSuppliers: "नाम, संपर्क या ईमेल द्वारा खोजें...",
    noSuppliersFound: "कोई आपूर्तिकर्ता नहीं मिला",
    noSuppliersYet: "आपने अभी तक कोई आपूर्तिकर्ता नहीं जोड़ा है।",
    due: "बकाया",
    settled: "निपटान",
    itemsSupplied: "आपूर्ति की गई वस्तुएं",
    manageSales: "आपके सभी रजिस्टरों में प्रत्येक लेनदेन।",
    searchSales: "चालान या ग्राहक द्वारा खोजें...",
    noSalesFound: "कोई बिक्री नहीं मिली",
    noSalesYet: "अभी तक कोई लेनदेन रिकॉर्ड नहीं किया गया है।",
    invoice: "बीजक",
    date: "तारीख",
    payment: "भुगतान",
    sync: "सिंक",
    total: "कुल",
    salesReturns: "बिक्री वापसी",
    manageReturns: "ग्राहकों को जारी किए गए रिफंड और एक्सचेंज।",
    processReturn: "वापसी प्रक्रिया",
    searchReturns: "संदर्भ या ग्राहक द्वारा खोजें...",
    noReturnsFound: "कोई रिटर्न नहीं मिला",
    noReturnsYet: "अभी तक कोई बिक्री रिटर्न दर्ज नहीं किया गया है।",
    ref: "संदर्भ",
    reason: "कारण",
    refund: "धनवापसी",
    purchases: "खरीद",
    managePurchases: "आपूर्तिकर्ताओं और खरीद आदेशों से आने वाली इन्वेंट्री।",
    newPurchase: "नई खरीद",
    searchPurchases: "पीओ या आपूर्तिकर्ता द्वारा खोजें...",
    noPurchasesFound: "कोई खरीद नहीं मिली",
    noPurchasesYet: "अभी तक कोई खरीद आदेश नहीं बनाया गया है।",
    po: "पीओ",
    supplier: "आपूर्तिकर्ता",
    expenses: "खर्च",
    manageExpenses: "सभी श्रेणियों में परिचालन लागत ट्रैक करें।",
    totalExpenses: "कुल खर्च",
    largestCategory: "सबसे बड़ी श्रेणी",
    pending: "लंबित",
    addExpense: "खर्च जोड़ें",
    searchExpenses: "श्रेणी या विवरण द्वारा खोजें...",
    noExpensesFound: "कोई खर्च नहीं मिला",
    noExpensesYet: "अभी तक कोई खर्च दर्ज नहीं किया गया है।",
    description: "विवरण",
    amount: "रकम",
    profile: "प्रोफ़ाइल",
    logout: "लॉग आउट",
    closeRegister: "रजिस्टर बंद करें",
    notifications: "सूचनाएं",
    help: "सहायता केंद्र",
    storeInfo: "स्टोर की जानकारी",
    storeName: "स्टोर का नाम",
    taxId: "टैक्स आईडी",
    address: "पता",
    phone: "फ़ोन",
    email: "ईमेल",
    currency: "मुद्रा",
    billing: "बिलिंग",
    appearance: "दिखावट",
    receipts: "रसीदें",
    paymentMethods: "भुगतान के तरीके",
    taxes: "कर (टैक्स)",
    users: "उपयोगकर्ता और भूमिकाएँ",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    newSale: "नई बिक्री",
    overview: "अवलोकन",
    catalog: "कैटलॉग",
    brands: "ब्रांड",
    units: "इकाइयाँ",
    stock: "स्टॉक",
    inventory: "इन्वेंटरी",
    adjustments: "समायोजन",
    transfers: "स्थानांतरण",
    stockHistory: "स्टॉक इतिहास",
    tradeB2B: "व्यापार और बी2बी",
    purchaseReturns: "खरीद वापसी",
    salesInvoices: "बिक्री चालान",
    quotations: "कोटेशन",
    deliveryChallans: "डिलीवरी चालान",
    people: "लोग",
    employees: "कर्मचारी",
    finance: "वित्त और खाते",
    accounts: "खातों का चार्ट",
    reports: "वित्तीय रिपोर्ट",
    services: "सेवाएं",
    repairs: "मरम्मत जॉब शीट",
    subscriptions: "सदस्यता",
    rentals: "किराये पर देना",
    marketing: "मार्केटिंग",
    coupons: "कूपन",
    giftCards: "गिफ्ट कार्ड",
    loyalty: "वफादारी",
    promotions: "प्रचार",
    system: "सिस्टम",
    superAdmin: "सुपर एडमिन",
    clientPortal: "ग्राहक पोर्टल",
    activityLog: "गतिविधि लॉग",
  },
  zh: {
    dashboard: "仪表板",
    pos: "POS 销售终端",
    products: "商品管理",
    categories: "商品分类",
    customers: "客户账簿",
    suppliers: "供应商",
    sales: "销售历史",
    settings: "系统设置",
    search: "搜索...",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    add: "新增",
    status: "状态",
    price: "价格",
    checkout: "结账",
    welcome: "欢迎回来",
    trialDaysLeft: "天试用剩余",
    emailVerificationRequired: "需要验证电子邮件",
    verifyEmail: "验证电子邮件",
    otpSentNotice: "请输入发送至您邮箱的6位验证码。",
    language: "语言",
    countryCode: "国家/地区代码",
    timezone: "时区",
    dateFormat: "日期格式",
    manageCatalog: "管理您的完整 SKU 目录、定价和库存阈值。",
    addProduct: "添加产品",
    searchProducts: "按名称、SKU 或条形码搜索...",
    noProductsFound: "未找到产品",
    adjustSearch: "尝试调整您的搜索。",
    noProductsYet: "您还没有添加任何产品。",
    product: "产品",
    sku: "SKU",
    category: "分类",
    manageCustomers: "管理客户关系、忠诚度和分类账。",
    addCustomer: "添加客户",
    searchCustomers: "按名称、电子邮件或电话搜索...",
    noCustomersFound: "未找到客户",
    noCustomersYet: "您还没有添加任何客户。",
    customer: "客户",
    contact: "联系方式",
    visits: "访问",
    lifetime: "终身",
    points: "积分",
    credit: "信用",
    wallet: "钱包",
    tier: "等级",
    actions: "操作",
    manageSuppliers: "管理供应商关系、购买历史记录和未结余额。",
    addSupplier: "添加供应商",
    searchSuppliers: "按名称、联系方式或电子邮件搜索...",
    noSuppliersFound: "未找到供应商",
    noSuppliersYet: "您还没有添加任何供应商。",
    due: "到期",
    settled: "已结算",
    itemsSupplied: "提供的物品",
    manageSales: "所有收银机的所有交易。",
    searchSales: "按发票或客户搜索...",
    noSalesFound: "未找到销售",
    noSalesYet: "尚未记录任何交易。",
    invoice: "发票",
    date: "日期",
    payment: "付款",
    sync: "同步",
    total: "总计",
    salesReturns: "销售退货",
    manageReturns: "向客户发出的退款和换货。",
    processReturn: "处理退货",
    searchReturns: "按参考或客户搜索...",
    noReturnsFound: "未找到退货",
    noReturnsYet: "尚未记录任何销售退货。",
    ref: "参考",
    reason: "原因",
    refund: "退款",
    purchases: "购买",
    managePurchases: "来自供应商和采购订单的入站库存。",
    newPurchase: "新购买",
    searchPurchases: "按采购订单或供应商搜索...",
    noPurchasesFound: "未找到购买记录",
    noPurchasesYet: "尚未创建任何采购订单。",
    po: "采购订单",
    supplier: "供应商",
    expenses: "费用",
    manageExpenses: "跨所有类别跟踪运营成本。",
    totalExpenses: "总费用",
    largestCategory: "最大类别",
    pending: "待定",
    addExpense: "添加费用",
    searchExpenses: "按类别或描述搜索...",
    noExpensesFound: "未找到费用",
    noExpensesYet: "尚未记录任何费用。",
    description: "描述",
    amount: "金额",
    profile: "个人资料",
    logout: "退出登录",
    closeRegister: "关闭收银机",
    notifications: "通知",
    help: "帮助中心",
    storeInfo: "店铺信息",
    storeName: "店名",
    taxId: "税号",
    address: "地址",
    phone: "电话",
    email: "电子邮件",
    currency: "货币",
    billing: "账单",
    appearance: "外观",
    receipts: "收据",
    paymentMethods: "付款方式",
    taxes: "税收",
    users: "用户和角色",
    active: "活跃",
    inactive: "不活跃",
    newSale: "新销售",
    overview: "概览",
    catalog: "目录",
    brands: "品牌",
    units: "单位",
    stock: "库存",
    inventory: "存货",
    adjustments: "调整",
    transfers: "调拨",
    stockHistory: "库存历史",
    tradeB2B: "贸易与 B2B",
    purchaseReturns: "采购退货",
    salesInvoices: "销售发票",
    quotations: "报价单",
    deliveryChallans: "交货单",
    people: "人员",
    employees: "员工",
    finance: "财务与账户",
    accounts: "会计科目表",
    reports: "财务报告",
    services: "服务",
    repairs: "维修工单",
    subscriptions: "订阅",
    rentals: "设备租赁",
    marketing: "营销",
    coupons: "优惠券",
    giftCards: "礼品卡",
    loyalty: "忠诚度",
    promotions: "促销",
    system: "系统",
    superAdmin: "超级管理员",
    clientPortal: "客户门户",
    activityLog: "活动日志",
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("pos_app_language");
      if (saved) return saved as LanguageCode;
    }
    return "en";
  });

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("pos_app_language", lang);
    }
  }, []);

  const currentOption = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  const dir = currentOption.dir;

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
      document.documentElement.dir = dir;
    }
  }, [language, dir]);

  const t = useCallback(
    (key: string): string => {
      return TRANSLATIONS[language]?.[key] || TRANSLATIONS["en"]?.[key] || key;
    },
    [language],
  );

  const value = useMemo(() => ({ language, setLanguage, t, dir }), [language, setLanguage, t, dir]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
