import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from "react";

export type LanguageCode =
  "en" | "es" | "fr" | "de" | "pt" | "ar" | "hi" | "bn" | "zh" | "ja" | "ru" | "id" | "tr";

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeName: string;
  flag: string;
  countryCode?: string;
  dir: "ltr" | "rtl";
}

export const LANGUAGES: LanguageOption[] = [
  { code: "en", label: "English", nativeName: "English", flag: "🇺🇸", countryCode: "US", dir: "ltr" },
  { code: "es", label: "Spanish", nativeName: "Español", flag: "🇪🇸", countryCode: "ES", dir: "ltr" },
  { code: "fr", label: "French", nativeName: "Français", flag: "🇫🇷", countryCode: "FR", dir: "ltr" },
  { code: "de", label: "German", nativeName: "Deutsch", flag: "🇩🇪", countryCode: "DE", dir: "ltr" },
  { code: "pt", label: "Portuguese", nativeName: "Português", flag: "🇧🇷", countryCode: "BR", dir: "ltr" },
  { code: "ar", label: "Arabic", nativeName: "العربية", flag: "🇸🇦", countryCode: "SA", dir: "rtl" },
  { code: "hi", label: "Hindi", nativeName: "हिंदी", flag: "🇮🇳", countryCode: "IN", dir: "ltr" },
  { code: "bn", label: "Bengali", nativeName: "বাংলা", flag: "🇧🇩", countryCode: "BD", dir: "ltr" },
  { code: "zh", label: "Chinese", nativeName: "中文", flag: "🇨🇳", countryCode: "CN", dir: "ltr" },
  { code: "ja", label: "Japanese", nativeName: "日本語", flag: "🇯🇵", countryCode: "JP", dir: "ltr" },
  { code: "ru", label: "Russian", nativeName: "Русский", flag: "🇷🇺", countryCode: "RU", dir: "ltr" },
  { code: "id", label: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩", countryCode: "ID", dir: "ltr" },
  { code: "tr", label: "Turkish", nativeName: "Türkçe", flag: "🇹🇷", countryCode: "TR", dir: "ltr" },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    pos: "POS Terminal",
    products: "Products",
    categories: "Categories",
    customers: "Customers",
    suppliers: "Suppliers",
    sales: "Sales History",
    settings: "Settings",
    search: "Search...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add New",
    status: "Status",
    price: "Price",
    checkout: "Checkout",
    welcome: "Welcome back",
    trialDaysLeft: "days left in trial",
    emailVerificationRequired: "Email Verification Required",
    verifyEmail: "Verify Email",
    otpSentNotice: "Enter 6-digit OTP code sent to your email.",
    language: "Language",
    country: "Country",
    countryCode: "Country Calling Code",
    timezone: "Timezone",
    dateFormat: "Date Format",
    manageCatalog: "Manage your full SKU catalog, pricing, and stock thresholds.",
    addProduct: "Add Product",
    appointments: "Appointments",
    tables: "Tables",
    kitchen: "Kitchen",
    searchProducts: "Search by name, SKU, or barcode...",
    noProductsFound: "No products found",
    adjustSearch: "Try adjusting your search.",
    noProductsYet: "You haven't added any products yet.",
    product: "Product",
    sku: "SKU",
    category: "Category",
    brand: "Brand",
    unitType: "Unit Type",
    selectCategory: "Select category...",
    selectBrand: "Select brand...",
    selectUnit: "Select unit...",
    selectVariant: "Select a variant",
    addToCart: "Add to Cart",
    filters: "Filters",
    spent: "Total Purchases",
    customerType: "Customer Type",
    items: "Items",
    manageCustomers: "Manage customer relationships, loyalty, and ledgers.",
    addCustomer: "Add Customer",
    searchCustomers: "Search by name, email, or phone...",
    noCustomersFound: "No customers found",
    noCustomersYet: "You haven't added any customers yet.",
    customer: "Customer",
    contact: "Contact",
    visits: "Visits",
    lifetime: "Lifetime",
    points: "Points",
    credit: "Credit",
    wallet: "Wallet",
    tier: "Tier",
    actions: "Actions",
    manageSuppliers: "Manage vendor relationships, purchase history, and outstanding balances.",
    addSupplier: "Add Supplier",
    searchSuppliers: "Search by name, contact, or email...",
    noSuppliersFound: "No suppliers found",
    noSuppliersYet: "You haven't added any suppliers yet.",
    due: "due",
    settled: "Settled",
    itemsSupplied: "Items supplied",
    manageSales: "Every transaction across all your registers.",
    searchSales: "Search by invoice or customer...",
    noSalesFound: "No sales found",
    noSalesYet: "No transactions have been recorded yet.",
    invoice: "Invoice",
    date: "Date",
    payment: "Payment",
    sync: "Sync",
    total: "Total",
    salesReturns: "Sales Returns",
    manageReturns: "Refunds and exchanges issued to customers.",
    processReturn: "Process Return",
    searchReturns: "Search by ref or customer...",
    noReturnsFound: "No returns found",
    noReturnsYet: "No sales returns have been recorded yet.",
    ref: "Ref",
    reason: "Reason",
    refund: "Refund",
    purchases: "Purchases",
    managePurchases: "Inbound inventory from suppliers and purchase orders.",
    newPurchase: "New Purchase",
    searchPurchases: "Search by PO or supplier...",
    noPurchasesFound: "No purchases found",
    noPurchasesYet: "No purchase orders have been created yet.",
    po: "PO",
    supplier: "Supplier",
    expenses: "Expenses",
    manageExpenses: "Track operational overheads across all categories.",
    totalExpenses: "Total Expenses",
    largestCategory: "Largest Category",
    pending: "Pending",
    addExpense: "Add Expense",
    searchExpenses: "Search by category or description...",
    noExpensesFound: "No expenses found",
    noExpensesYet: "No expenses have been recorded yet.",
    description: "Description",
    amount: "Amount",
    profile: "Profile",
    logout: "Log Out",
    closeRegister: "Close Register",
    notifications: "Notifications",
    help: "Help Center",
    storeInfo: "Store Information",
    storeName: "Store Name",
    taxId: "Tax ID / VAT / GSTIN",
    address: "Address",
    phone: "Phone Number",
    email: "Email",
    currency: "Currency",
    billing: "Billing & Plans",
    appearance: "Appearance",
    receipts: "Receipts Studio",
    paymentMethods: "Payment Methods",
    taxes: "Taxes & Levies",
    users: "Users & Roles",
    active: "Active",
    inactive: "Inactive",
    newSale: "New Sale",
    overview: "Overview",
    catalog: "Catalog",
    brands: "Brands",
    units: "Units",
    stock: "Stock",
    inventory: "Inventory",
    adjustments: "Stock Adjustments",
    transfers: "Stock Transfers",
    stockHistory: "Stock History",
    tradeB2B: "Trade & B2B",
    purchaseReturns: "Purchase Returns",
    salesInvoices: "Sales Invoices",
    quotations: "Quotations",
    deliveryChallans: "Delivery Challans",
    people: "People",
    employees: "Employees",
    finance: "Finance & Accounts",
    accounts: "Chart of Accounts",
    accounting_reports: "Accounting Reports",
    reports: "Financial Reports",
    services: "Services & Verticals",
    repairs: "Repair Job Sheets",
    subscriptions: "Subscriptions",
    rentals: "Equipment Rentals",
    marketing: "Marketing",
    coupons: "Coupons",
    giftCards: "Gift Cards",
    loyalty: "Loyalty",
    promotions: "Promotions",
    system: "System",
    superAdmin: "Super Admin SaaS",
    clientPortal: "Client Portal",
    activityLog: "Activity Log",
    billingSales: "Billing & Sales",
    inventoryCatalog: "Inventory & Catalog",
    purchasesSuppliers: "Purchases & Vendors",
    customersLoyalty: "Customers & Khata",
    accountsExpenses: "Accounts & Expenses",
    servicesOperations: "Services & Operations",
    settingsSystem: "Store & Settings",
    salesFulfillment: "Sales & Fulfillment",
    purchasesVendors: "Purchases & Vendors",
    customersMarketing: "Customers & Marketing",
    financeAccounts: "Finance & Accounts",
    administration: "Administration",
    productsCatalog: "Products Catalog",
  },
  es: {
    dashboard: "Panel de Control",
    pos: "Terminal Punto de Venta",
    products: "Productos",
    categories: "Categorías",
    customers: "Clientes y Cuentas",
    suppliers: "Proveedores",
    sales: "Historial de Ventas",
    settings: "Configuración",
    search: "Buscar...",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    add: "Añadir Nuevo",
    status: "Estado",
    price: "Precio",
    checkout: "Cobrar",
    welcome: "Bienvenido de nuevo",
    trialDaysLeft: "días restantes de prueba",
    emailVerificationRequired: "Verificación de Correo Requerida",
    verifyEmail: "Verificar Correo",
    otpSentNotice: "Ingrese el código OTP de 6 dígitos enviado a su correo.",
    language: "Idioma",
    country: "País",
    countryCode: "Código de País",
    timezone: "Zona Horaria",
    dateFormat: "Formato de Fecha",
    manageCatalog: "Administre su catálogo completo de productos, precios e inventario.",
    addProduct: "Añadir Producto",
    appointments: "Citas",
    tables: "Mesas",
    kitchen: "Cocina",
    searchProducts: "Buscar por nombre, SKU o código de barras...",
    noProductsFound: "No se encontraron productos",
    adjustSearch: "Intente ajustar su búsqueda.",
    noProductsYet: "Aún no ha añadido productos.",
    product: "Producto",
    sku: "SKU",
    category: "Categoría",
    brand: "Marca",
    unitType: "Unidad",
    selectCategory: "Seleccionar categoría...",
    selectBrand: "Seleccionar marca...",
    selectUnit: "Seleccionar unidad...",
    selectVariant: "Seleccionar variante",
    addToCart: "Añadir al Carrito",
    filters: "Filtros",
    spent: "Compras Totales",
    customerType: "Tipo de Cliente",
    items: "Artículos",
    manageCustomers: "Administre clientes, crédito, puntos de fidelidad y saldos.",
    addCustomer: "Añadir Cliente",
    searchCustomers: "Buscar por nombre, correo o teléfono...",
    noCustomersFound: "No se encontraron clientes",
    noCustomersYet: "Aún no ha añadido clientes.",
    customer: "Cliente",
    contact: "Contacto",
    visits: "Visitas",
    lifetime: "Total Histórico",
    points: "Puntos",
    credit: "Crédito",
    wallet: "Billetera",
    tier: "Nivel",
    actions: "Acciones",
    manageSuppliers: "Gestione proveedores, órdenes de compra y saldos pendientes.",
    addSupplier: "Añadir Proveedor",
    searchSuppliers: "Buscar por nombre, contacto o correo...",
    noSuppliersFound: "No se encontraron proveedores",
    noSuppliersYet: "Aún no ha añadido proveedores.",
    due: "pendiente",
    settled: "Liquidado",
    itemsSupplied: "Artículos suministrados",
    manageSales: "Todas las transacciones en sus cajas registradoras.",
    searchSales: "Buscar por factura o cliente...",
    noSalesFound: "No se encontraron ventas",
    noSalesYet: "Aún no se han registrado ventas.",
    invoice: "Factura",
    date: "Fecha",
    payment: "Pago",
    sync: "Sincronización",
    total: "Total",
    salesReturns: "Devoluciones de Venta",
    manageReturns: "Reembolsos y cambios emitidos a clientes.",
    processReturn: "Procesar Devolución",
    searchReturns: "Buscar por referencia o cliente...",
    noReturnsFound: "No se encontraron devoluciones",
    noReturnsYet: "No hay devoluciones registradas.",
    ref: "Ref.",
    reason: "Motivo",
    refund: "Reembolso",
    purchases: "Compras",
    managePurchases: "Inventario recibido y órdenes de compra a proveedores.",
    newPurchase: "Nueva Compra",
    searchPurchases: "Buscar por orden de compra o proveedor...",
    noPurchasesFound: "No se encontraron compras",
    noPurchasesYet: "No hay órdenes de compra registradas.",
    po: "OC",
    supplier: "Proveedor",
    expenses: "Gastos",
    manageExpenses: "Control de costos operativos y gastos generales.",
    totalExpenses: "Gastos Totales",
    largestCategory: "Mayor Categoría",
    pending: "Pendiente",
    addExpense: "Añadir Gasto",
    searchExpenses: "Buscar por categoría o descripción...",
    noExpensesFound: "No se encontraron gastos",
    noExpensesYet: "No hay gastos registrados.",
    description: "Descripción",
    amount: "Monto",
    profile: "Perfil",
    logout: "Cerrar Sesión",
    closeRegister: "Cerrar Caja",
    notifications: "Notificaciones",
    help: "Centro de Ayuda",
    storeInfo: "Información de la Tienda",
    storeName: "Nombre de la Tienda",
    taxId: "Identificación Fiscal / IVA / RFC / CIF",
    address: "Dirección",
    phone: "Teléfono",
    email: "Correo Electrónico",
    currency: "Moneda",
    billing: "Facturación y Planes",
    appearance: "Apariencia",
    receipts: "Diseño de Recibos",
    paymentMethods: "Métodos de Pago",
    taxes: "Impuestos y Tasas",
    users: "Usuarios y Roles",
    active: "Activo",
    inactive: "Inactivo",
    newSale: "Nueva Venta",
    overview: "Resumen General",
    catalog: "Catálogo",
    brands: "Marcas",
    units: "Unidades",
    stock: "Stock",
    inventory: "Inventario",
    adjustments: "Ajustes de Stock",
    transfers: "Traslados de Stock",
    stockHistory: "Historial de Stock",
    tradeB2B: "Comercio B2B",
    purchaseReturns: "Devoluciones a Proveedores",
    salesInvoices: "Facturas de Venta",
    quotations: "Cotizaciones",
    deliveryChallans: "Guías de Remisión",
    people: "Personal",
    employees: "Empleados",
    finance: "Finanzas y Contabilidad",
    accounts: "Plan de Cuentas",
    accounting_reports: "Reportes Contables",
    reports: "Reportes Financieros",
    services: "Servicios y Especialidades",
    repairs: "Órdenes de Reparación",
    subscriptions: "Suscripciones",
    rentals: "Alquiler de Equipos",
    marketing: "Marketing",
    coupons: "Cupones",
    giftCards: "Tarjetas de Regalo",
    loyalty: "Fidelización",
    promotions: "Promociones",
    system: "Sistema",
    superAdmin: "Super Administrador",
    clientPortal: "Portal de Clientes",
    activityLog: "Registro de Actividad",
    billingSales: "Ventas y Facturación",
    inventoryCatalog: "Inventario y Catálogo",
    purchasesSuppliers: "Compras y Proveedores",
    customersLoyalty: "Clientes y Fidelización",
    accountsExpenses: "Cuentas y Gastos",
    servicesOperations: "Servicios y Operaciones",
    settingsSystem: "Tienda y Configuración",
    salesFulfillment: "Ventas y Entregas",
    purchasesVendors: "Compras y Proveedores",
    customersMarketing: "Clientes y Mercadeo",
    financeAccounts: "Finanzas y Cuentas",
    administration: "Administración",
    productsCatalog: "Catálogo de Productos",
  },
  fr: {
    dashboard: "Tableau de Bord",
    pos: "Caisse Enregistreuse",
    products: "Produits",
    categories: "Catégories",
    customers: "Clients",
    suppliers: "Fournisseurs",
    sales: "Historique des Ventes",
    settings: "Paramètres",
    search: "Rechercher...",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    status: "Statut",
    price: "Prix",
    checkout: "Encaisser",
    welcome: "Bienvenue",
    trialDaysLeft: "jours d'essai restants",
    emailVerificationRequired: "Vérification de l'E-mail Requise",
    verifyEmail: "Vérifier l'E-mail",
    otpSentNotice: "Entrez le code OTP à 6 chiffres envoyé à votre adresse e-mail.",
    language: "Langue",
    country: "Pays",
    countryCode: "Indicatif Téléphonique",
    timezone: "Fuseau Horaire",
    dateFormat: "Format de Date",
    manageCatalog: "Gérez votre catalogue complet, vos prix et vos seuils de stock.",
    addProduct: "Ajouter un Produit",
    appointments: "Rendez-vous",
    tables: "Tables",
    kitchen: "Cuisine",
    searchProducts: "Rechercher par nom, SKU ou code-barres...",
    noProductsFound: "Aucun produit trouvé",
    adjustSearch: "Essayez d'ajuster votre recherche.",
    noProductsYet: "Vous n'avez pas encore ajouté de produit.",
    product: "Produit",
    sku: "SKU",
    category: "Catégorie",
    brand: "Marque",
    unitType: "Type d'Unité",
    selectCategory: "Sélectionner la catégorie...",
    selectBrand: "Sélectionner la marque...",
    selectUnit: "Sélectionner l'unité...",
    selectVariant: "Sélectionner une variante",
    addToCart: "Ajouter au Panier",
    filters: "Filtres",
    spent: "Achats Cumulés",
    customerType: "Type de Client",
    items: "Articles",
    manageCustomers: "Gérez les comptes clients, la fidélité et les soldes.",
    addCustomer: "Ajouter un Client",
    searchCustomers: "Rechercher par nom, e-mail ou téléphone...",
    noCustomersFound: "Aucun client trouvé",
    noCustomersYet: "Vous n'avez pas encore ajouté de client.",
    customer: "Client",
    contact: "Contact",
    visits: "Visites",
    lifetime: "Total Historique",
    points: "Points",
    credit: "Crédit",
    wallet: "Portefeuille",
    tier: "Niveau",
    actions: "Actions",
    manageSuppliers: "Gérez les fournisseurs, commandes d'achat et soldes dus.",
    addSupplier: "Ajouter un Fournisseur",
    searchSuppliers: "Rechercher par nom, contact ou e-mail...",
    noSuppliersFound: "Aucun fournisseur trouvé",
    noSuppliersYet: "Vous n'avez pas encore ajouté de fournisseur.",
    due: "dû",
    settled: "Réglé",
    itemsSupplied: "Articles fournis",
    manageSales: "Toutes les transactions effectuées sur vos caisses.",
    searchSales: "Rechercher par facture ou client...",
    noSalesFound: "Aucune vente trouvée",
    noSalesYet: "Aucune vente enregistrée pour le moment.",
    invoice: "Facture",
    date: "Date",
    payment: "Paiement",
    sync: "Synchronisation",
    total: "Total",
    salesReturns: "Retours de Vente",
    manageReturns: "Remboursements et échanges émis pour les clients.",
    processReturn: "Traiter le Retour",
    searchReturns: "Rechercher par réf. ou client...",
    noReturnsFound: "Aucun retour trouvé",
    noReturnsYet: "Aucun retour enregistré.",
    ref: "Réf.",
    reason: "Motif",
    refund: "Remboursement",
    purchases: "Achats",
    managePurchases: "Commandes fournisseurs et réceptions de stock.",
    newPurchase: "Nouvel Achat",
    searchPurchases: "Rechercher par bon de commande ou fournisseur...",
    noPurchasesFound: "Aucun achat trouvé",
    noPurchasesYet: "Aucun bon de commande créé.",
    po: "BC",
    supplier: "Fournisseur",
    expenses: "Dépenses",
    manageExpenses: "Suivi des frais généraux et coûts d'exploitation.",
    totalExpenses: "Dépenses Totales",
    largestCategory: "Catégorie Principale",
    pending: "En attente",
    addExpense: "Ajouter une Dépense",
    searchExpenses: "Rechercher par catégorie ou description...",
    noExpensesFound: "Aucune dépense trouvée",
    noExpensesYet: "Aucune dépense enregistrée.",
    description: "Description",
    amount: "Montant",
    profile: "Profil",
    logout: "Déconnexion",
    closeRegister: "Clôturer la Caisse",
    notifications: "Notifications",
    help: "Centre d'Aide",
    storeInfo: "Informations du Magasin",
    storeName: "Nom du Magasin",
    taxId: "Numéro TVA / SIRET / Identifiant Fiscal",
    address: "Adresse",
    phone: "Numéro de Téléphone",
    email: "E-mail",
    currency: "Devise",
    billing: "Facturation & Abonnements",
    appearance: "Apparence",
    receipts: "Studio des Tickets",
    paymentMethods: "Moyens de Paiement",
    taxes: "Taxes et TVA",
    users: "Utilisateurs et Rôles",
    active: "Actif",
    inactive: "Inactif",
    newSale: "Nouvelle Vente",
    overview: "Vue d'Ensemble",
    catalog: "Catalogue",
    brands: "Marques",
    units: "Unités",
    stock: "Stock",
    inventory: "Inventaire",
    adjustments: "Ajustements de Stock",
    transfers: "Transferts de Stock",
    stockHistory: "Historique du Stock",
    tradeB2B: "Commerce B2B",
    purchaseReturns: "Retours Fournisseurs",
    salesInvoices: "Factures Clients",
    quotations: "Devis",
    deliveryChallans: "Bons de Livraison",
    people: "Équipe",
    employees: "Employés",
    finance: "Finance & Comptabilité",
    accounts: "Plan Comptable",
    accounting_reports: "Rapports Comptables",
    reports: "Rapports Financiers",
    services: "Services & Activités",
    repairs: "Fiches de Réparation",
    subscriptions: "Abonnements",
    rentals: "Locations de Matériel",
    marketing: "Marketing",
    coupons: "Bons de Réduction",
    giftCards: "Cartes Cadeaux",
    loyalty: "Programme de Fidélité",
    promotions: "Promotions",
    system: "Système",
    superAdmin: "Super Administrateur",
    clientPortal: "Portail Client",
    activityLog: "Journal d'Activité",
    billingSales: "Ventes et Facturation",
    inventoryCatalog: "Inventaire et Catalogue",
    purchasesSuppliers: "Achats et Fournisseurs",
    customersLoyalty: "Clients et Fidélité",
    accountsExpenses: "Comptes et Dépenses",
    servicesOperations: "Services et Opérations",
    settingsSystem: "Boutique et Paramètres",
    salesFulfillment: "Ventes et Expéditions",
    purchasesVendors: "Achats et Vendeurs",
    customersMarketing: "Clients et Marketing",
    financeAccounts: "Finance et Comptabilité",
    administration: "Administration",
    productsCatalog: "Catalogue de Produits",
  },
  de: {
    dashboard: "Dashboard",
    pos: "Kassenterminal (POS)",
    products: "Artikel & Produkte",
    categories: "Kategorien",
    customers: "Kundenkartei",
    suppliers: "Lieferanten",
    sales: "Verkaufshistorie",
    settings: "Einstellungen",
    search: "Suchen...",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    add: "Neu Hinzufügen",
    status: "Status",
    price: "Preis",
    checkout: "Bezahlen",
    welcome: "Willkommen zurück",
    trialDaysLeft: "Tage Testphase verbleibend",
    emailVerificationRequired: "E-Mail-Verifizierung Erforderlich",
    verifyEmail: "E-Mail Bestätigen",
    otpSentNotice: "Geben Sie den 6-stelligen OTP-Code ein, der an Ihre E-Mail gesendet wurde.",
    language: "Sprache",
    country: "Land",
    countryCode: "Ländervorwahl",
    timezone: "Zeitzone",
    dateFormat: "Datumsformat",
    manageCatalog: "Verwalten Sie Ihren vollständigen Artikelstamm, Preise und Bestände.",
    addProduct: "Artikel Hinzufügen",
    appointments: "Termine",
    tables: "Tische",
    kitchen: "Küche",
    searchProducts: "Nach Name, SKU oder Barcode suchen...",
    noProductsFound: "Keine Artikel gefunden",
    adjustSearch: "Passen Sie Ihre Suche an.",
    noProductsYet: "Sie haben noch keine Artikel angelegt.",
    product: "Artikel",
    sku: "SKU / Art.-Nr.",
    category: "Kategorie",
    brand: "Marke",
    unitType: "Einheit",
    selectCategory: "Kategorie wählen...",
    selectBrand: "Marke wählen...",
    selectUnit: "Einheit wählen...",
    selectVariant: "Variante auswählen",
    addToCart: "In den Warenkorb",
    filters: "Filter",
    spent: "Gesamtumsatz",
    customerType: "Kundentyp",
    items: "Artikel",
    manageCustomers: "Kundenbeziehungen, Treuepunkte und Kundenkonten verwalten.",
    addCustomer: "Kunde Anlegen",
    searchCustomers: "Nach Name, E-Mail oder Telefon suchen...",
    noCustomersFound: "Keine Kunden gefunden",
    noCustomersYet: "Sie haben noch keine Kunden angelegt.",
    customer: "Kunde",
    contact: "Kontakt",
    visits: "Besuche",
    lifetime: "Gesamtumsatz",
    points: "Punkte",
    credit: "Guthaben / Limit",
    wallet: "Kundenkonto",
    tier: "Stufe",
    actions: "Aktionen",
    manageSuppliers: "Lieferanten, Einkäufe und offene Posten verwalten.",
    addSupplier: "Lieferant Anlegen",
    searchSuppliers: "Nach Name, Ansprechpartner oder E-Mail suchen...",
    noSuppliersFound: "Keine Lieferanten gefunden",
    noSuppliersYet: "Sie haben noch keine Lieferanten angelegt.",
    due: "fällig",
    settled: "Ausgeglichen",
    itemsSupplied: "Gelieferte Artikel",
    manageSales: "Jeder Kassiervorgang über alle Terminals hinweg.",
    searchSales: "Nach Rechnungs-Nr. oder Kunde suchen...",
    noSalesFound: "Keine Verkäufe gefunden",
    noSalesYet: "Noch keine Transaktionen erfasst.",
    invoice: "Rechnung / Beleg",
    date: "Datum",
    payment: "Zahlungsart",
    sync: "Sync",
    total: "Gesamtbetrag",
    salesReturns: "Retouren & Gutschriften",
    manageReturns: "Rückerstattungen und Umtausche für Kunden.",
    processReturn: "Retoure Erfassen",
    searchReturns: "Nach Beleg oder Kunde suchen...",
    noReturnsFound: "Keine Retouren gefunden",
    noReturnsYet: "Noch keine Retouren erfasst.",
    ref: "Ref.",
    reason: "Grund",
    refund: "Erstattung",
    purchases: "Wareneingang / Einkauf",
    managePurchases: "Bestellungen bei Lieferanten und Wareneingänge.",
    newPurchase: "Neue Bestellung",
    searchPurchases: "Nach Bestell-Nr. oder Lieferant suchen...",
    noPurchasesFound: "Keine Einkäufe gefunden",
    noPurchasesYet: "Noch keine Bestellungen erstellt.",
    po: "Bestellung",
    supplier: "Lieferant",
    expenses: "Betriebsausgaben",
    manageExpenses: "Laufende Geschäftsausgaben und Kostenstellen erfassen.",
    totalExpenses: "Gesamtausgaben",
    largestCategory: "Größte Kostenart",
    pending: "Ausstehend",
    addExpense: "Ausgabe Erfassen",
    searchExpenses: "Nach Kategorie oder Betreff suchen...",
    noExpensesFound: "Keine Ausgaben gefunden",
    noExpensesYet: "Noch keine Ausgaben erfasst.",
    description: "Beschreibung",
    amount: "Betrag",
    profile: "Profil",
    logout: "Abmelden",
    closeRegister: "Kassenabschluss (Z-Bon)",
    notifications: "Benachrichtigungen",
    help: "Hilfezentrum",
    storeInfo: "Unternehmensdaten",
    storeName: "Geschäftsname",
    taxId: "USt-IdNr. / Steuer-Nr.",
    address: "Anschrift",
    phone: "Telefonnummer",
    email: "E-Mail",
    currency: "Währung",
    billing: "Abrechnung & Pläne",
    appearance: "Erscheinungsbild",
    receipts: "Beleg- & Druckvorlagen",
    paymentMethods: "Zahlungsmethoden",
    taxes: "Steuersätze (MwSt / USt)",
    users: "Benutzer & Rechte",
    active: "Aktiv",
    inactive: "Inaktiv",
    newSale: "Neuer Verkauf",
    overview: "Übersicht",
    catalog: "Katalog",
    brands: "Marken",
    units: "Einheiten",
    stock: "Lagerbestand",
    inventory: "Inventur & Lager",
    adjustments: "Bestandskorrekturen",
    transfers: "Umlagerungen",
    stockHistory: "Lagerhistorie",
    tradeB2B: "B2B-Handel",
    purchaseReturns: "Rücksendungen an Lieferanten",
    salesInvoices: "Ausgangsrechnungen",
    quotations: "Angebote",
    deliveryChallans: "Lieferscheine",
    people: "Personal",
    employees: "Mitarbeiter",
    finance: "Finanzen & Buchhaltung",
    accounts: "Kontenrahmen",
    accounting_reports: "Buchhaltungsberichte",
    reports: "Finanzberichte",
    services: "Dienstleistungen",
    repairs: "Reparaturaufträge",
    subscriptions: "Abonnements",
    rentals: "Geräteverleih",
    marketing: "Marketing",
    coupons: "Gutscheine & Coupons",
    giftCards: "Geschenkkarten",
    loyalty: "Treueprogramm",
    promotions: "Aktionen & Rabatte",
    system: "System",
    superAdmin: "Super Admin",
    clientPortal: "Kundenportal",
    activityLog: "Aktivitätsprotokoll",
    billingSales: "Verkauf & Abrechnung",
    inventoryCatalog: "Lager & Katalog",
    purchasesSuppliers: "Einkauf & Lieferanten",
    customersLoyalty: "Kunden & Treue",
    accountsExpenses: "Konten & Ausgaben",
    servicesOperations: "Service & Betrieb",
    settingsSystem: "Geschäft & Einstellungen",
    salesFulfillment: "Verkauf & Abwicklung",
    purchasesVendors: "Einkauf & Lieferanten",
    customersMarketing: "Kunden & Marketing",
    financeAccounts: "Finanzen & Konten",
    administration: "Verwaltung",
    productsCatalog: "Artikelkatalog",
  },
  pt: {
    dashboard: "Painel de Controle",
    pos: "Frente de Caixa (PDV)",
    products: "Produtos",
    categories: "Categorias",
    customers: "Clientes",
    suppliers: "Fornecedores",
    sales: "Histórico de Vendas",
    settings: "Configurações",
    search: "Pesquisar...",
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Excluir",
    edit: "Editar",
    add: "Adicionar Novo",
    status: "Status",
    price: "Preço",
    checkout: "Finalizar Venda",
    welcome: "Bem-vindo de volta",
    trialDaysLeft: "dias restantes de teste",
    emailVerificationRequired: "Verificação de E-mail Necessária",
    verifyEmail: "Verificar E-mail",
    otpSentNotice: "Digite o código OTP de 6 dígitos enviado para seu e-mail.",
    language: "Idioma",
    country: "País",
    countryCode: "Código do País",
    timezone: "Fuso Horário",
    dateFormat: "Formato de Data",
    manageCatalog: "Gerencie seu catálogo completo, preços e estoque.",
    addProduct: "Adicionar Produto",
    appointments: "Agendamentos",
    tables: "Mesas",
    kitchen: "Cozinha",
    searchProducts: "Buscar por nome, SKU ou código de barras...",
    noProductsFound: "Nenhum produto encontrado",
    adjustSearch: "Tente ajustar sua busca.",
    noProductsYet: "Você ainda não adicionou nenhum produto.",
    product: "Produto",
    sku: "SKU",
    category: "Categoria",
    brand: "Marca",
    unitType: "Unidade",
    selectCategory: "Selecionar categoria...",
    selectBrand: "Selecionar marca...",
    selectUnit: "Selecionar unidade...",
    selectVariant: "Selecionar variação",
    addToCart: "Adicionar ao Carrinho",
    filters: "Filtros",
    spent: "Compras Totais",
    customerType: "Tipo de Cliente",
    items: "Itens",
    manageCustomers: "Gerencie clientes, pontos de fidelidade e crediário.",
    addCustomer: "Adicionar Cliente",
    searchCustomers: "Buscar por nome, e-mail ou telefone...",
    noCustomersFound: "Nenhum cliente encontrado",
    noCustomersYet: "Nenhum cliente cadastrado ainda.",
    customer: "Cliente",
    contact: "Contato",
    visits: "Visitas",
    lifetime: "Total Histórico",
    points: "Pontos",
    credit: "Crédito / Limite",
    wallet: "Carteira",
    tier: "Nível",
    actions: "Ações",
    manageSuppliers: "Gerencie fornecedores, compras e valores a pagar.",
    addSupplier: "Adicionar Fornecedor",
    searchSuppliers: "Buscar por nome, contato ou e-mail...",
    noSuppliersFound: "Nenhum fornecedor encontrado",
    noSuppliersYet: "Nenhum fornecedor cadastrado ainda.",
    due: "a pagar",
    settled: "Quitado",
    itemsSupplied: "Itens fornecidos",
    manageSales: "Todas as operações e cupons emitidos nos caixas.",
    searchSales: "Buscar por cupom/nota ou cliente...",
    noSalesFound: "Nenhuma venda encontrada",
    noSalesYet: "Nenhuma venda registrada até o momento.",
    invoice: "Nota / Cupom",
    date: "Data",
    payment: "Forma de Pagamento",
    sync: "Sincronizar",
    total: "Total",
    salesReturns: "Trocas e Devoluções",
    manageReturns: "Reembolsos e devoluções realizadas a clientes.",
    processReturn: "Registrar Devolução",
    searchReturns: "Buscar por ref. ou cliente...",
    noReturnsFound: "Nenhuma devolução encontrada",
    noReturnsYet: "Nenhuma devolução registrada.",
    ref: "Ref.",
    reason: "Motivo",
    refund: "Reembolso",
    purchases: "Compras e Entradas",
    managePurchases: "Entrada de mercadorias e pedidos de compra.",
    newPurchase: "Nova Compra",
    searchPurchases: "Buscar por pedido ou fornecedor...",
    noPurchasesFound: "Nenhuma compra encontrada",
    noPurchasesYet: "Nenhum pedido de compra criado ainda.",
    po: "Pedido",
    supplier: "Fornecedor",
    expenses: "Despesas Operacionais",
    manageExpenses: "Acompanhe despesas fixas, variáveis e custos.",
    totalExpenses: "Total de Despesas",
    largestCategory: "Maior Categoria",
    pending: "Pendente",
    addExpense: "Lançar Despesa",
    searchExpenses: "Buscar por categoria ou descrição...",
    noExpensesFound: "Nenhuma despesa encontrada",
    noExpensesYet: "Nenhuma despesa lançada ainda.",
    description: "Descrição",
    amount: "Valor",
    profile: "Perfil",
    logout: "Sair",
    closeRegister: "Fechar Caixa",
    notifications: "Notificações",
    help: "Central de Ajuda",
    storeInfo: "Dados da Empresa",
    storeName: "Nome Fantasia / Razão Social",
    taxId: "CNPJ / CPF / Inscrição Estadual",
    address: "Endereço",
    phone: "Telefone / WhatsApp",
    email: "E-mail",
    currency: "Moeda",
    billing: "Planos e Cobrança",
    appearance: "Aparência",
    receipts: "Impressão de Recibos",
    paymentMethods: "Formas de Pagamento",
    taxes: "Tributos e Impostos",
    users: "Usuários e Permissões",
    active: "Ativo",
    inactive: "Inativo",
    newSale: "Nova Venda",
    overview: "Visão Geral",
    catalog: "Catálogo",
    brands: "Marcas",
    units: "Unidades",
    stock: "Estoque",
    inventory: "Inventário e Estoque",
    adjustments: "Ajustes de Estoque",
    transfers: "Transferências de Estoque",
    stockHistory: "Movimentação de Estoque",
    tradeB2B: "Vendas B2B / Atacado",
    purchaseReturns: "Devoluções a Fornecedores",
    salesInvoices: "Notas Fiscais de Venda",
    quotations: "Orçamentos",
    deliveryChallans: "Romaneios de Entrega",
    people: "Equipe",
    employees: "Funcionários",
    finance: "Financeiro e Contábil",
    accounts: "Plano de Contas",
    accounting_reports: "Relatórios Contábeis",
    reports: "Relatórios Financeiros",
    services: "Serviços e Atendimentos",
    repairs: "Ordens de Serviço (OS)",
    subscriptions: "Assinaturas e Recorrência",
    rentals: "Locação de Equipamentos",
    marketing: "Marketing",
    coupons: "Cupons de Desconto",
    giftCards: "Vales-Presente",
    loyalty: "Programa de Pontos",
    promotions: "Promoções",
    system: "Sistema",
    superAdmin: "Super Administrador",
    clientPortal: "Portal do Cliente",
    activityLog: "Registro de Auditoria",
    billingSales: "Faturamento e Vendas",
    inventoryCatalog: "Estoque e Catálogo",
    purchasesSuppliers: "Compras e Fornecedores",
    customersLoyalty: "Clientes e Fidelidade",
    accountsExpenses: "Contas e Despesas",
    servicesOperations: "Serviços e Operações",
    settingsSystem: "Loja e Configurações",
    salesFulfillment: "Vendas e Entregas",
    purchasesVendors: "Compras e Fornecedores",
    customersMarketing: "Clientes e Marketing",
    financeAccounts: "Finanças e Contabilidade",
    administration: "Administração",
    productsCatalog: "Catálogo de Produtos",
  },
  ja: {
    dashboard: "ダッシュボード",
    pos: "POS レジ端末",
    products: "商品一覧",
    categories: "カテゴリー",
    customers: "顧客管理",
    suppliers: "仕入先",
    sales: "売上履歴",
    settings: "システム設定",
    search: "検索...",
    save: "保存",
    cancel: "キャンセル",
    delete: "削除",
    edit: "編集",
    add: "新規追加",
    status: "ステータス",
    price: "価格",
    checkout: "会計・精算",
    welcome: "お帰りなさい",
    trialDaysLeft: "日トライアル残り",
    emailVerificationRequired: "メール認証が必要です",
    verifyEmail: "メールを認証",
    otpSentNotice: "メールに送信された6桁の確認コードを入力してください。",
    language: "言語",
    country: "国",
    countryCode: "国番号",
    timezone: "タイムゾーン",
    dateFormat: "日付形式",
    manageCatalog: "商品カタログ、価格設定、在庫基準値を管理します。",
    addProduct: "商品を追加",
    appointments: "予約管理",
    tables: "テーブル",
    kitchen: "キッチン",
    searchProducts: "商品名、SKU、バーコードで検索...",
    noProductsFound: "該当する商品が見つかりません",
    adjustSearch: "検索条件を変更してください。",
    noProductsYet: "まだ商品が登録されていません。",
    product: "商品",
    sku: "商品コード (SKU)",
    category: "カテゴリー",
    brand: "ブランド",
    unitType: "単位",
    selectCategory: "カテゴリーを選択...",
    selectBrand: "ブランドを選択...",
    selectUnit: "単位を選択...",
    selectVariant: "バリエーションを選択",
    addToCart: "カートに追加",
    filters: "フィルター",
    spent: "累計購入額",
    customerType: "顧客区分",
    items: "商品アイテム",
    manageCustomers: "顧客情報、ポイント、売掛残高を管理します。",
    addCustomer: "顧客を追加",
    searchCustomers: "名前、メール、電話番号で検索...",
    noCustomersFound: "顧客が見つかりません",
    noCustomersYet: "まだ顧客が登録されていません。",
    customer: "顧客",
    contact: "連絡先",
    visits: "来店回数",
    lifetime: "生涯売上",
    points: "ポイント",
    credit: "売掛限度額",
    wallet: "残高",
    tier: "ランク",
    actions: "操作",
    manageSuppliers: "仕入先、発注履歴、買掛残高を管理します。",
    addSupplier: "仕入先を追加",
    searchSuppliers: "名前、連絡先、メールで検索...",
    noSuppliersFound: "仕入先が見つかりません",
    noSuppliersYet: "まだ仕入先が登録されていません。",
    due: "未払残高",
    settled: "精算済",
    itemsSupplied: "供給品目",
    manageSales: "すべてのレジ端末での取引記録。",
    searchSales: "伝票番号または顧客名で検索...",
    noSalesFound: "売上が見つかりません",
    noSalesYet: "まだ取引が記録されていません。",
    invoice: "レシート・領収書",
    date: "日付",
    payment: "支払方法",
    sync: "同期",
    total: "合計",
    salesReturns: "返品・返金",
    manageReturns: "顧客への返金および商品交換の管理。",
    processReturn: "返品処理",
    searchReturns: "参照番号または顧客で検索...",
    noReturnsFound: "返品記録がありません",
    noReturnsYet: "返品記録はありません。",
    ref: "参照番号",
    reason: "理由",
    refund: "返金額",
    purchases: "仕入・発注",
    managePurchases: "仕入先からの入荷および発注書管理。",
    newPurchase: "新規発注",
    searchPurchases: "発注番号または仕入先で検索...",
    noPurchasesFound: "仕入記録がありません",
    noPurchasesYet: "発注書はまだ作成されていません。",
    po: "発注書",
    supplier: "仕入先",
    expenses: "経費管理",
    manageExpenses: "各カテゴリーの運営費や諸経費を追跡します。",
    totalExpenses: "経費合計",
    largestCategory: "最大費目",
    pending: "保留中",
    addExpense: "経費を登録",
    searchExpenses: "カテゴリーや詳細で検索...",
    noExpensesFound: "経費が見つかりません",
    noExpensesYet: "経費はまだ登録されていません。",
    description: "詳細",
    amount: "金額",
    profile: "プロフィール",
    logout: "ログアウト",
    closeRegister: "レジ締め処理",
    notifications: "通知",
    help: "ヘルプセンター",
    storeInfo: "店舗情報",
    storeName: "店舗名・会社名",
    taxId: "適格請求書登録番号 / 法人番号",
    address: "住所",
    phone: "電話番号",
    email: "メールアドレス",
    currency: "通貨",
    billing: "プランと請求",
    appearance: "外観",
    receipts: "レシート設定",
    paymentMethods: "決済方法",
    taxes: "消費税率設定",
    users: "ユーザーと権限",
    active: "有効",
    inactive: "無効",
    newSale: "新規会計",
    overview: "概要",
    catalog: "商品カタログ",
    brands: "ブランド",
    units: "単位",
    stock: "在庫数",
    inventory: "在庫・棚卸",
    adjustments: "在庫調整",
    transfers: "店舗間移動",
    stockHistory: "入出庫履歴",
    tradeB2B: "B2B・卸取引",
    purchaseReturns: "仕入返品",
    salesInvoices: "請求書発行",
    quotations: "見積書",
    deliveryChallans: "納品書",
    people: "スタッフ",
    employees: "従業員",
    finance: "財務・会計",
    accounts: "勘定科目表",
    accounting_reports: "財務諸表",
    reports: "売上・財務レポート",
    services: "サービス",
    repairs: "修理伝票",
    subscriptions: "定期購入・サブスク",
    rentals: "機器レンタル",
    marketing: "販促・マーケティング",
    coupons: "クーポン",
    giftCards: "ギフト券",
    loyalty: "ポイント会員",
    promotions: "プロモーション",
    system: "システム",
    superAdmin: "システム管理者",
    clientPortal: "顧客ポータル",
    activityLog: "操作ログ",
    billingSales: "売上・レジ会計",
    inventoryCatalog: "在庫・商品カタログ",
    purchasesSuppliers: "仕入・発注管理",
    customersLoyalty: "顧客・ポイント",
    accountsExpenses: "出納・経費",
    servicesOperations: "サービス・業務",
    settingsSystem: "店舗・基本設定",
    salesFulfillment: "販売・納品",
    purchasesVendors: "仕入・取引先",
    customersMarketing: "顧客・マーケティング",
    financeAccounts: "財務・会計",
    administration: "管理機能",
    productsCatalog: "商品一覧",
  },
  ru: {
    dashboard: "Панель управления",
    pos: "POS Терминал / Касса",
    products: "Товары",
    categories: "Категории",
    customers: "Клиенты",
    suppliers: "Поставщики",
    sales: "История продаж",
    settings: "Настройки",
    search: "Поиск...",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    add: "Добавить",
    status: "Статус",
    price: "Цена",
    checkout: "Оплата / Чек",
    welcome: "С возвращением",
    trialDaysLeft: "дней пробного периода осталось",
    emailVerificationRequired: "Требуется подтверждение E-mail",
    verifyEmail: "Подтвердить E-mail",
    otpSentNotice: "Введите 6-значный код подтверждения, отправленный на ваш E-mail.",
    language: "Язык",
    country: "Страна",
    countryCode: "Телефонный код",
    timezone: "Часовой пояс",
    dateFormat: "Формат даты",
    manageCatalog: "Управляйте каталогом товаров, ценами и складскими остатками.",
    addProduct: "Добавить товар",
    appointments: "Записи",
    tables: "Столы",
    kitchen: "Кухня",
    searchProducts: "Поиск по названию, артикулу или штрихкоду...",
    noProductsFound: "Товары не найдены",
    adjustSearch: "Попробуйте изменить запрос.",
    noProductsYet: "Вы еще не добавили ни одного товара.",
    product: "Товар",
    sku: "Артикул / SKU",
    category: "Категория",
    brand: "Бренд",
    unitType: "Ед. изм.",
    selectCategory: "Выберите категорию...",
    selectBrand: "Выберите бренд...",
    selectUnit: "Выберите единицу...",
    selectVariant: "Выберите вариант",
    addToCart: "В корзину",
    filters: "Фильтры",
    spent: "Сумма покупок",
    customerType: "Тип клиента",
    items: "Позиции",
    manageCustomers: "База клиентов, бонусные баллы и взаиморасчеты.",
    addCustomer: "Добавить клиента",
    searchCustomers: "Поиск по имени, email или телефону...",
    noCustomersFound: "Клиенты не найдены",
    noCustomersYet: "Вы еще не добавили клиентов.",
    customer: "Клиент",
    contact: "Контакты",
    visits: "Визиты",
    lifetime: "LTV",
    points: "Баллы",
    credit: "Кредит / Лимит",
    wallet: "Баланс",
    tier: "Уровень",
    actions: "Действия",
    manageSuppliers: "Поставщики, история закупок и задолженности.",
    addSupplier: "Добавить поставщика",
    searchSuppliers: "Поиск по названию, контакту или email...",
    noSuppliersFound: "Поставщики не найдены",
    noSuppliersYet: "Вы еще не добавили поставщиков.",
    due: "долг",
    settled: "Оплачено",
    itemsSupplied: "Поставлено товаров",
    manageSales: "Все кассовые чеки и транзакции.",
    searchSales: "Поиск по чеку или клиенту...",
    noSalesFound: "Продажи не найдены",
    noSalesYet: "Продаж пока нет.",
    invoice: "Чек / Накладная",
    date: "Дата",
    payment: "Оплата",
    sync: "Синхронизация",
    total: "Итого",
    salesReturns: "Возвраты товаров",
    manageReturns: "Оформление возвратов и обменов покупателям.",
    processReturn: "Оформить возврат",
    searchReturns: "Поиск по номеру или клиенту...",
    noReturnsFound: "Возвраты не найдены",
    noReturnsYet: "Возвратов пока не было.",
    ref: "№",
    reason: "Причина",
    refund: "Возврат средств",
    purchases: "Закупки / Приход",
    managePurchases: "Поступление товаров от поставщиков и заказы.",
    newPurchase: "Новая закупка",
    searchPurchases: "Поиск по заказу или поставщику...",
    noPurchasesFound: "Закупки не найдены",
    noPurchasesYet: "Заказов на закупку пока нет.",
    po: "Заказ №",
    supplier: "Поставщик",
    expenses: "Расходы",
    manageExpenses: "Учет операционных и административных расходов.",
    totalExpenses: "Всего расходов",
    largestCategory: "Основная статья",
    pending: "В ожидании",
    addExpense: "Добавить расход",
    searchExpenses: "Поиск по категории или описанию...",
    noExpensesFound: "Расходы не найдены",
    noExpensesYet: "Расходов пока нет.",
    description: "Описание",
    amount: "Сумма",
    profile: "Профиль",
    logout: "Выйти",
    closeRegister: "Закрыть смену (Z-отчет)",
    notifications: "Уведомления",
    help: "База знаний",
    storeInfo: "Реквизиты магазина",
    storeName: "Название организации",
    taxId: "ИНН / ОГРН / КПП",
    address: "Адрес",
    phone: "Телефон",
    email: "E-mail",
    currency: "Валюта",
    billing: "Тарифы и оплата",
    appearance: "Интерфейс",
    receipts: "Шаблоны чеков",
    paymentMethods: "Способы оплаты",
    taxes: "Ставки НДС",
    users: "Сотрудники и роли",
    active: "Активен",
    inactive: "Неактивен",
    newSale: "Новая продажа",
    overview: "Обзор",
    catalog: "Каталог",
    brands: "Бренды",
    units: "Единицы измерения",
    stock: "Остатки",
    inventory: "Склад и инвентаризация",
    adjustments: "Списания и оприходования",
    transfers: "Перемещения",
    stockHistory: "История склада",
    tradeB2B: "Оптовая торговля B2B",
    purchaseReturns: "Возвраты поставщикам",
    salesInvoices: "Счета на оплату",
    quotations: "Коммерческие предложения",
    deliveryChallans: "Транспортные накладные",
    people: "Персонал",
    employees: "Сотрудники",
    finance: "Финансы и бухгалтерия",
    accounts: "План счетов",
    accounting_reports: "Бухгалтерские отчеты",
    reports: "Финансовые отчеты",
    services: "Услуги",
    repairs: "Заказ-наряды на ремонт",
    subscriptions: "Подписки",
    rentals: "Аренда оборудования",
    marketing: "Маркетинг",
    coupons: "Промокоды",
    giftCards: "Подарочные карты",
    loyalty: "Программа лояльности",
    promotions: "Акции",
    system: "Система",
    superAdmin: "Суперадминистратор",
    clientPortal: "Личный кабинет клиента",
    activityLog: "Журнал аудита",
    billingSales: "Продажи и касса",
    inventoryCatalog: "Склад и каталог",
    purchasesSuppliers: "Закупки и поставщики",
    customersLoyalty: "Клиенты и лояльность",
    accountsExpenses: "Счета и расходы",
    servicesOperations: "Услуги и сервис",
    settingsSystem: "Магазин и настройки",
    salesFulfillment: "Продажи и отгрузка",
    purchasesVendors: "Закупки и поставщики",
    customersMarketing: "Клиенты и маркетинг",
    financeAccounts: "Финансы и счета",
    administration: "Администрирование",
    productsCatalog: "Каталог товаров",
  },
  id: {
    dashboard: "Dashboard",
    pos: "Kasir POS",
    products: "Produk",
    categories: "Kategori",
    customers: "Pelanggan",
    suppliers: "Pemasok",
    sales: "Riwayat Penjualan",
    settings: "Pengaturan",
    search: "Cari...",
    save: "Simpan",
    cancel: "Batal",
    delete: "Hapus",
    edit: "Ubah",
    add: "Tambah Baru",
    status: "Status",
    price: "Harga",
    checkout: "Bayar",
    welcome: "Selamat Datang",
    trialDaysLeft: "hari uji coba tersisa",
    emailVerificationRequired: "Verifikasi Email Diperlukan",
    verifyEmail: "Verifikasi Email",
    otpSentNotice: "Masukkan 6 digit kode OTP yang dikirim ke email Anda.",
    language: "Bahasa",
    country: "Negara",
    countryCode: "Kode Negara",
    timezone: "Zona Waktu",
    dateFormat: "Format Tanggal",
    manageCatalog: "Kelola seluruh katalog produk, harga, dan stok Anda.",
    addProduct: "Tambah Produk",
    appointments: "Janji Temu",
    tables: "Meja",
    kitchen: "Dapur",
    searchProducts: "Cari berdasarkan nama, SKU, atau barcode...",
    noProductsFound: "Produk tidak ditemukan",
    adjustSearch: "Coba sesuaikan pencarian Anda.",
    noProductsYet: "Anda belum menambahkan produk apa pun.",
    product: "Produk",
    sku: "SKU",
    category: "Kategori",
    brand: "Merek",
    unitType: "Satuan",
    selectCategory: "Pilih kategori...",
    selectBrand: "Pilih merek...",
    selectUnit: "Pilih satuan...",
    selectVariant: "Pilih varian",
    addToCart: "Tambah ke Keranjang",
    filters: "Filter",
    spent: "Total Belanja",
    customerType: "Tipe Pelanggan",
    items: "Barang",
    manageCustomers: "Kelola pelanggan, poin loyalitas, dan catatan piutang.",
    addCustomer: "Tambah Pelanggan",
    searchCustomers: "Cari nama, email, atau telepon...",
    noCustomersFound: "Pelanggan tidak ditemukan",
    noCustomersYet: "Belum ada pelanggan.",
    customer: "Pelanggan",
    contact: "Kontak",
    visits: "Kunjungan",
    lifetime: "Total Transaksi",
    points: "Poin",
    credit: "Batas Kredit",
    wallet: "Dompet",
    tier: "Level",
    actions: "Aksi",
    manageSuppliers: "Kelola pemasok, riwayat pembelian, dan utang.",
    addSupplier: "Tambah Pemasok",
    searchSuppliers: "Cari nama, kontak, atau email...",
    noSuppliersFound: "Pemasok tidak ditemukan",
    noSuppliersYet: "Belum ada pemasok.",
    due: "jatuh tempo",
    settled: "Lunas",
    itemsSupplied: "Barang dipasok",
    manageSales: "Seluruh transaksi dari semua mesin kasir.",
    searchSales: "Cari struk atau pelanggan...",
    noSalesFound: "Penjualan tidak ditemukan",
    noSalesYet: "Belum ada transaksi.",
    invoice: "Faktur / Struk",
    date: "Tanggal",
    payment: "Metode Pembayaran",
    sync: "Sinkronisasi",
    total: "Total",
    salesReturns: "Retur Penjualan",
    manageReturns: "Pengembalian dana dan penukaran barang pelanggan.",
    processReturn: "Proses Retur",
    searchReturns: "Cari ref atau pelanggan...",
    noReturnsFound: "Retur tidak ditemukan",
    noReturnsYet: "Belum ada retur penjualan.",
    ref: "Ref",
    reason: "Alasan",
    refund: "Pengembalian Dana",
    purchases: "Pembelian",
    managePurchases: "Penerimaan barang masuk dari pemasok dan PO.",
    newPurchase: "Pembelian Baru",
    searchPurchases: "Cari PO atau pemasok...",
    noPurchasesFound: "Pembelian tidak ditemukan",
    noPurchasesYet: "Belum ada pesanan pembelian.",
    po: "PO",
    supplier: "Pemasok",
    expenses: "Pengeluaran",
    manageExpenses: "Pantau biaya operasional dan pengeluaran toko.",
    totalExpenses: "Total Pengeluaran",
    largestCategory: "Kategori Terbesar",
    pending: "Tertunda",
    addExpense: "Tambah Pengeluaran",
    searchExpenses: "Cari kategori atau deskripsi...",
    noExpensesFound: "Pengeluaran tidak ditemukan",
    noExpensesYet: "Belum ada pengeluaran dicatat.",
    description: "Deskripsi",
    amount: "Jumlah",
    profile: "Profil",
    logout: "Keluar",
    closeRegister: "Tutup Kasir",
    notifications: "Notifikasi",
    help: "Pusat Bantuan",
    storeInfo: "Informasi Toko",
    storeName: "Nama Toko / Badan Usaha",
    taxId: "NPWP / NIB / Identitas Pajak",
    address: "Alamat",
    phone: "Nomor Telepon",
    email: "Email",
    currency: "Mata Uang",
    billing: "Paket & Tagihan",
    appearance: "Tampilan",
    receipts: "Desain Struk",
    paymentMethods: "Metode Pembayaran",
    taxes: "Pajak (PPN)",
    users: "Pengguna & Hak Akses",
    active: "Aktif",
    inactive: "Nonaktif",
    newSale: "Transaksi Baru",
    overview: "Ringkasan",
    catalog: "Katalog",
    brands: "Merek",
    units: "Satuan",
    stock: "Stok",
    inventory: "Inventori & Stok",
    adjustments: "Penyesuaian Stok",
    transfers: "Transfer Stok",
    stockHistory: "Riwayat Stok",
    tradeB2B: "Perdagangan B2B",
    purchaseReturns: "Retur Pembelian",
    salesInvoices: "Faktur Penjualan",
    quotations: "Penawaran Harga",
    deliveryChallans: "Surat Jalan",
    people: "Karyawan",
    employees: "Staf",
    finance: "Keuangan & Akuntansi",
    accounts: "Bagan Akun (COA)",
    accounting_reports: "Laporan Akuntansi",
    reports: "Laporan Keuangan",
    services: "Layanan & Servis",
    repairs: "Tiket Reparasi",
    subscriptions: "Langganan",
    rentals: "Sewa Peralatan",
    marketing: "Pemasaran",
    coupons: "Kupon Diskon",
    giftCards: "Kartu Hadiah",
    loyalty: "Loyalitas",
    promotions: "Promosi",
    system: "Sistem",
    superAdmin: "Super Admin",
    clientPortal: "Portal Klien",
    activityLog: "Log Aktivitas",
    billingSales: "Penjualan & Kasir",
    inventoryCatalog: "Stok & Katalog",
    purchasesSuppliers: "Pembelian & Pemasok",
    customersLoyalty: "Pelanggan & Kas",
    accountsExpenses: "Akun & Beban",
    servicesOperations: "Layanan & Operasional",
    settingsSystem: "Toko & Pengaturan",
    salesFulfillment: "Penjualan & Pengiriman",
    purchasesVendors: "Pembelian & Vendor",
    customersMarketing: "Pelanggan & Pemasaran",
    financeAccounts: "Keuangan & Akun",
    administration: "Administrasi",
    productsCatalog: "Katalog Produk",
  },
  tr: {
    dashboard: "Kontrol Paneli",
    pos: "POS Satış Terminali",
    products: "Ürünler",
    categories: "Kategoriler",
    customers: "Müşteriler",
    suppliers: "Tedarikçiler",
    sales: "Satış Geçmişi",
    settings: "Ayarlar",
    search: "Ara...",
    save: "Kaydet",
    cancel: "İptal",
    delete: "Sil",
    edit: "Düzenle",
    add: "Yeni Ekle",
    status: "Durum",
    price: "Fiyat",
    checkout: "Ödeme / Satış",
    welcome: "Tekrar Hoş Geldiniz",
    trialDaysLeft: "gün deneme süresi kaldı",
    emailVerificationRequired: "E-posta Doğrulaması Gerekli",
    verifyEmail: "E-postayı Doğrula",
    otpSentNotice: "E-postanıza gönderilen 6 haneli doğrulama kodunu girin.",
    language: "Dil",
    country: "Ülke",
    countryCode: "Ülke Kodu",
    timezone: "Saat Dilimi",
    dateFormat: "Tarih Formatı",
    manageCatalog: "Ürün kataloğunuzu, fiyatlarınızı ve stok limitlerinizi yönetin.",
    addProduct: "Ürün Ekle",
    appointments: "Randevular",
    tables: "Masalar",
    kitchen: "Mutfak",
    searchProducts: "İsim, barkod veya stok kodu ile ara...",
    noProductsFound: "Ürün bulunamadı",
    adjustSearch: "Aramanızı değiştirmeyi deneyin.",
    noProductsYet: "Henüz ürün eklemediniz.",
    product: "Ürün",
    sku: "Stok Kodu (SKU)",
    category: "Kategori",
    brand: "Marka",
    unitType: "Birim",
    selectCategory: "Kategori seçin...",
    selectBrand: "Marka seçin...",
    selectUnit: "Birim seçin...",
    selectVariant: "Varyant seçin",
    addToCart: "Sepete Ekle",
    filters: "Filtreler",
    spent: "Toplam Harcama",
    customerType: "Müşteri Tipi",
    items: "Ürünler",
    manageCustomers: "Müşteri ilişkileri, sadakat puanları ve veresiye takibi.",
    addCustomer: "Müşteri Ekle",
    searchCustomers: "İsim, e-posta veya telefon ile ara...",
    noCustomersFound: "Müşteri bulunamadı",
    noCustomersYet: "Henüz müşteri eklenmedi.",
    customer: "Müşteri",
    contact: "İletişim",
    visits: "Ziyaret",
    lifetime: "Toplam Ciro",
    points: "Puan",
    credit: "Kredi Limiti",
    wallet: "Bakiye",
    tier: "Seviye",
    actions: "İşlemler",
    manageSuppliers: "Tedarikçiler, satın alma geçmişi ve borç bakiyeleri.",
    addSupplier: "Tedarikçi Ekle",
    searchSuppliers: "İsim, irtibat veya e-posta ile ara...",
    noSuppliersFound: "Tedarikçi bulunamadı",
    noSuppliersYet: "Henüz tedarikçi eklenmedi.",
    due: "vadesi gelen",
    settled: "Ödendi",
    itemsSupplied: "Tedarik edilen ürünler",
    manageSales: "Tüm kasalardan yapılan tüm işlemler.",
    searchSales: "Fatura veya müşteriye göre ara...",
    noSalesFound: "Satış bulunamadı",
    noSalesYet: "Henüz bir işlem kaydedilmedi.",
    invoice: "Fiş / Fatura",
    date: "Tarih",
    payment: "Ödeme Yöntemi",
    sync: "Senkronizasyon",
    total: "Toplam",
    salesReturns: "Satış İadeleri",
    manageReturns: "Müşterilere yapılan iade ve değişimler.",
    processReturn: "İade İşlemi Yap",
    searchReturns: "Referans veya müşteriye göre ara...",
    noReturnsFound: "İade bulunamadı",
    noReturnsYet: "Henüz bir satış iadesi kaydedilmedi.",
    ref: "Ref",
    reason: "Neden",
    refund: "İade Tutarı",
    purchases: "Satın Alma / Alışlar",
    managePurchases: "Tedarikçilerden gelen stok ve siparişler.",
    newPurchase: "Yeni Alış Faturası",
    searchPurchases: "Sipariş no veya tedarikçiye göre ara...",
    noPurchasesFound: "Satın alma kaydı bulunamadı",
    noPurchasesYet: "Henüz bir satın alma emri oluşturulmadı.",
    po: "Sipariş No",
    supplier: "Tedarikçi",
    expenses: "Giderler",
    manageExpenses: "Tüm kategorilerde işletme giderlerini takip edin.",
    totalExpenses: "Toplam Gider",
    largestCategory: "En Büyük Kategori",
    pending: "Beklemede",
    addExpense: "Gider Ekle",
    searchExpenses: "Kategori veya açıklamaya göre ara...",
    noExpensesFound: "Gider bulunamadı",
    noExpensesYet: "Henüz bir gider kaydedilmedi.",
    description: "Açıklama",
    amount: "Tutar",
    profile: "Profil",
    logout: "Çıkış Yap",
    closeRegister: "Kasa Kapat (Z Raporu)",
    notifications: "Bildirimler",
    help: "Yardım Merkezi",
    storeInfo: "Mağaza Bilgileri",
    storeName: "Mağaza / Firma Adı",
    taxId: "Vergi Kimlik No / T.C. No",
    address: "Adres",
    phone: "Telefon",
    email: "E-posta",
    currency: "Para Birimi",
    billing: "Faturalandırma ve Paketler",
    appearance: "Görünüm",
    receipts: "Fiş Tasarımı",
    paymentMethods: "Ödeme Yöntemleri",
    taxes: "Vergiler (KDV)",
    users: "Kullanıcılar ve Roller",
    active: "Aktif",
    inactive: "Pasif",
    newSale: "Yeni Satış",
    overview: "Genel Bakış",
    catalog: "Katalog",
    brands: "Markalar",
    units: "Birimler",
    stock: "Stok",
    inventory: "Stok ve Envanter",
    adjustments: "Stok Düzeltmeleri",
    transfers: "Stok Transferleri",
    stockHistory: "Stok Geçmişi",
    tradeB2B: "B2B Ticaret",
    purchaseReturns: "Alış İadeleri",
    salesInvoices: "Satış Faturaları",
    quotations: "Teklifler",
    deliveryChallans: "İrsaliyeler",
    people: "Personel",
    employees: "Çalışanlar",
    finance: "Finans ve Muhasebe",
    accounts: "Hesap Planı",
    accounting_reports: "Muhasebe Raporları",
    reports: "Finansal Raporlar",
    services: "Hizmetler",
    repairs: "Teknik Servis Fişleri",
    subscriptions: "Abonelikler",
    rentals: "Kiralama İşlemleri",
    marketing: "Pazarlama",
    coupons: "Kuponlar",
    giftCards: "Hediye Kartları",
    loyalty: "Müşteri Sadakati",
    promotions: "Promosyonlar",
    system: "Sistem",
    superAdmin: "Süper Yönetici",
    clientPortal: "Müşteri Portalı",
    activityLog: "Aktivite Günlüğü",
    billingSales: "Satış ve Faturalandırma",
    inventoryCatalog: "Envanter ve Katalog",
    purchasesSuppliers: "Satın Alma ve Tedarikçiler",
    customersLoyalty: "Müşteriler ve Veresiye",
    accountsExpenses: "Hesaplar ve Giderler",
    servicesOperations: "Hizmetler ve Operasyonlar",
    settingsSystem: "Mağaza ve Ayarlar",
    salesFulfillment: "Satış ve Teslimat",
    purchasesVendors: "Satın Alma ve Tedarikçiler",
    customersMarketing: "Müşteriler ve Pazarlama",
    financeAccounts: "Finans ve Muhasebe",
    administration: "Yönetim",
    productsCatalog: "Ürün Kataloğu",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    pos: "পজ টার্মিনাল",
    products: "পণ্য তালিকা",
    categories: "ক্যাটাগরি",
    customers: "গ্রাহক খাতা",
    suppliers: "সরবরাহকারী",
    sales: "বিক্রয় ইতিহাস",
    settings: "সেটিংস",
    search: "অনুসন্ধান করুন...",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল",
    delete: "মুছুন",
    edit: "সম্পাদনা",
    add: "নতুন যুক্ত করুন",
    status: "স্ট্যাটাস",
    price: "মূল্য",
    checkout: "চেকআউট",
    welcome: "স্বাগতম",
    trialDaysLeft: "দিন ট্রায়াল বাকী",
    emailVerificationRequired: "ইমেইল ভেরিফিকেশন প্রয়োজন",
    verifyEmail: "ইমেইল ভেরিফাই করুন",
    otpSentNotice: "আপনার ইমেইলে পাঠানো ৬-সংখ্যার OTP কোডটি লিখুন।",
    language: "ভাষা",
    country: "দেশ",
    countryCode: "কান্ট্রি কোড",
    timezone: "টাইমজোন",
    dateFormat: "তারিখ ফরম্যাট",
    manageCatalog: "আপনার সম্পূর্ণ এসকেইউ ক্যাটালগ, প্রাইসিং এবং স্টক পরিচালনা করুন।",
    addProduct: "পণ্য যোগ করুন",
    appointments: "অ্যাপয়েন্টমেন্ট",
    tables: "টেবিল",
    kitchen: "রান্নাঘর",
    searchProducts: "নাম, এসকেইউ অথবা বারকোড দিয়ে খুঁজুন...",
    noProductsFound: "কোনো পণ্য পাওয়া যায়নি",
    adjustSearch: "আপনার অনুসন্ধান পরিবর্তন করে দেখুন।",
    noProductsYet: "আপনি এখনও কোনো পণ্য যোগ করেননি।",
    product: "পণ্য",
    sku: "এসকেইউ",
    category: "ক্যাটাগরি",
    brand: "ব্র্যান্ড",
    unitType: "একক প্রকার",
    selectCategory: "ক্যাটাগরি নির্বাচন করুন...",
    selectBrand: "ব্র্যান্ড নির্বাচন করুন...",
    selectUnit: "একক নির্বাচন করুন...",
    selectVariant: "ভেরিয়েন্ট নির্বাচন করুন",
    addToCart: "কার্টে যোগ করুন",
    filters: "ফিল্টার",
    spent: "মোট কেনাকাটা",
    customerType: "গ্রাহকের ধরন",
    items: "আইটেম",
    manageCustomers: "গ্রাহকদের সম্পর্ক, লয়্যালটি এবং লেজার পরিচালনা করুন।",
    addCustomer: "গ্রাহক যোগ করুন",
    searchCustomers: "নাম, ইমেইল অথবা ফোন নম্বর দিয়ে খুঁজুন...",
    noCustomersFound: "কোনো গ্রাহক পাওয়া যায়নি",
    noCustomersYet: "আপনি এখনও কোনো গ্রাহক যোগ করেননি।",
    customer: "গ্রাহক",
    contact: "যোগাযোগ",
    visits: "ভিজিট",
    lifetime: "আজীবন",
    points: "পয়েন্ট",
    credit: "বাকি",
    wallet: "ওয়ালেট",
    tier: "টিয়ার",
    actions: "অ্যাকশন",
    manageSuppliers: "ভেন্ডর সম্পর্ক, ক্রয়ের ইতিহাস এবং বকেয়া ব্যালেন্স পরিচালনা করুন।",
    addSupplier: "সাপ্লায়ার যোগ করুন",
    searchSuppliers: "নাম, যোগাযোগ অথবা ইমেইল দিয়ে খুঁজুন...",
    noSuppliersFound: "কোনো সাপ্লায়ার পাওয়া যায়নি",
    noSuppliersYet: "আপনি এখনও কোনো সাপ্লায়ার যোগ করেননি।",
    due: "বাকি",
    settled: "পরিশোধিত",
    itemsSupplied: "সরবরাহকৃত আইটেম",
    manageSales: "আপনার সকল রেজিস্টারের প্রতিটি লেনদেন।",
    searchSales: "ইনভয়েস বা গ্রাহক দ্বারা খুঁজুন...",
    noSalesFound: "কোনো বিক্রয় পাওয়া যায়নি",
    noSalesYet: "এখনো কোনো লেনদেন রেকর্ড করা হয়নি।",
    invoice: "ইনভয়েস",
    date: "তারিখ",
    payment: "পেমেন্ট",
    sync: "সিঙ্ক",
    total: "মোট",
    salesReturns: "বিক্রয় ফেরত",
    manageReturns: "গ্রাহকদের দেওয়া রিফান্ড এবং পরিবর্তনসমূহ।",
    processReturn: "রিটার্ন প্রক্রিয়া করুন",
    searchReturns: "রেফারেন্স বা গ্রাহক দ্বারা খুঁজুন...",
    noReturnsFound: "কোনো রিটার্ন পাওয়া যায়নি",
    noReturnsYet: "এখনো কোনো বিক্রয় ফেরত রেকর্ড করা হয়নি।",
    ref: "রেফ",
    reason: "কারণ",
    refund: "রিফান্ড",
    purchases: "ক্রয়",
    managePurchases: "সাপ্লায়ার এবং পারচেজ অর্ডার থেকে আগত ইনভেন্টরি।",
    newPurchase: "নতুন ক্রয়",
    searchPurchases: "পিও (PO) বা সাপ্লায়ার দ্বারা খুঁজুন...",
    noPurchasesFound: "কোনো ক্রয় পাওয়া যায়নি",
    noPurchasesYet: "এখনো কোনো পারচেজ অর্ডার তৈরি করা হয়নি।",
    po: "পিও (PO)",
    supplier: "সাপ্লায়ার",
    expenses: "খরচ",
    manageExpenses: "সব ক্যাটাগরি জুড়ে অপারেটিং খরচ ট্র্যাক করুন।",
    totalExpenses: "মোট খরচ",
    largestCategory: "সবচেয়ে বড় ক্যাটাগরি",
    pending: "অমীমাংসিত",
    addExpense: "খরচ যোগ করুন",
    searchExpenses: "ক্যাটাগরি বা বিবরণ দ্বারা খুঁজুন...",
    noExpensesFound: "কোনো খরচ পাওয়া যায়নি",
    noExpensesYet: "এখনো কোনো খরচ রেকর্ড করা হয়নি।",
    description: "বিবরণ",
    amount: "পরিমাণ",
    profile: "প্রোফাইল",
    logout: "লগ আউট",
    closeRegister: "রেজিস্টার বন্ধ করুন",
    notifications: "নোটিফিকেশন",
    help: "সাহায্য কেন্দ্র",
    storeInfo: "স্টোর তথ্য",
    storeName: "স্টোরের নাম",
    taxId: "ট্যাক্স আইডি",
    address: "ঠিকানা",
    phone: "ফোন নম্বর",
    email: "ইমেইল",
    currency: "মুদ্রা",
    billing: "বিলিং",
    appearance: "চেহারা",
    receipts: "রসিদ",
    paymentMethods: "পেমেন্ট পদ্ধতি",
    taxes: "ট্যাক্স",
    users: "ইউজার এবং রোল",
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    newSale: "নতুন বিক্রয়",
    overview: "ওভারভিউ",
    catalog: "ক্যাটালগ",
    brands: "ব্র্যান্ড",
    units: "ইউনিট",
    stock: "স্টক",
    inventory: "ইনভেন্টরি",
    adjustments: "অ্যাডজাস্টমেন্ট",
    transfers: "ট্রান্সফার",
    stockHistory: "স্টক হিস্ট্রি",
    tradeB2B: "ট্রেড ও বিটুবি",
    purchaseReturns: "ক্রয় ফেরত",
    salesInvoices: "বিক্রয় ইনভয়েস",
    quotations: "কোটেশন",
    deliveryChallans: "ডেলিভারি চালান",
    people: "লোকজন",
    employees: "কর্মচারী",
    finance: "অর্থ ও হিসাব",
    accounts: "হিসাবের তালিকা",
    accounting_reports: "অ্যাকাউন্টিং রিপোর্ট",
    reports: "আর্থিক প্রতিবেদন",
    services: "পরিষেবা",
    repairs: "মেরামত জব শিট",
    subscriptions: "সাবস্ক্রিপশন",
    rentals: "ভাড়া",
    marketing: "মার্কেটিং",
    coupons: "কুপন",
    giftCards: "গিফট কার্ড",
    loyalty: "লয়্যালটি",
    promotions: "প্রোমোশন",
    system: "সিস্টেম",
    superAdmin: "সুপার অ্যাডমিন",
    clientPortal: "ক্লাইন্ট পোর্টাল",
    activityLog: "অ্যাক্টিভিটি লগ",
    billingSales: "বিলিং এবং বিক্রয়",
    inventoryCatalog: "ইনভেন্টরি এবং ক্যাটালগ",
    purchasesSuppliers: "ক্রয় এবং বিক্রেতা",
    customersLoyalty: "গ্রাহক এবং খাতা",
    accountsExpenses: "অ্যাকাউন্ট এবং খরচ",
    servicesOperations: "সেবা এবং অপারেশন",
    settingsSystem: "স্টোর এবং সেটিংস",
    salesFulfillment: "বিক্রয় এবং পরিপূর্ণতা",
    purchasesVendors: "ক্রয় এবং বিক্রেতা",
    customersMarketing: "গ্রাহক এবং বিপণন",
    financeAccounts: "অর্থ ও হিসাব",
    administration: "প্রশাসন",
    productsCatalog: "পণ্য ক্যাটালগ",
  },
  ar: {
    dashboard: "لوحة التحكم",
    pos: "نقطة البيع",
    products: "المنتجات",
    categories: "الفئات",
    customers: "العملاء",
    suppliers: "الموردون",
    sales: "المبيعات",
    settings: "الإعدادات",
    search: "بحث...",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة جديد",
    status: "الحالة",
    price: "السعر",
    checkout: "الدفع والتسديد",
    welcome: "مرحباً بعودتك",
    trialDaysLeft: "أيام متبقية في التجربة",
    emailVerificationRequired: "مطلوب تأكيد البريد الإلكتروني",
    verifyEmail: "تأكيد البريد",
    otpSentNotice: "أدخل رمز التحقق المكون من 6 أرقام المرسل إلى بريدك.",
    language: "اللغة",
    country: "الدولة",
    countryCode: "رمز الدولة",
    timezone: "المنطقة الزمنية",
    dateFormat: "تنسيق التاريخ",
    manageCatalog: "إدارة الكتالوج الكامل والتسعير وحدود المخزون.",
    addProduct: "إضافة منتج",
    appointments: "المواعيد",
    tables: "الطاولات",
    kitchen: "المطبخ",
    searchProducts: "ابحث بالاسم، أو الباركود...",
    noProductsFound: "لم يتم العثور على منتجات",
    adjustSearch: "حاول تعديل البحث.",
    noProductsYet: "لم تقم بإضافة أي منتجات بعد.",
    product: "المنتج",
    sku: "SKU",
    category: "الفئة",
    brand: "العلامة التجارية",
    unitType: "نوع الوحدة",
    selectCategory: "اختر الفئة...",
    selectBrand: "اختر العلامة التجارية...",
    selectUnit: "اختر الوحدة...",
    selectVariant: "اختر متغير",
    addToCart: "أضف إلى السلة",
    filters: "الفلاتر",
    spent: "إجمالي المشتريات",
    customerType: "نوع العميل",
    items: "الأصناف",
    manageCustomers: "إدارة علاقات العملاء والولاء والدفاتر.",
    addCustomer: "إضافة عميل",
    searchCustomers: "البحث بالاسم والبريد الإلكتروني أو الهاتف...",
    noCustomersFound: "لم يتم العثور على عملاء",
    noCustomersYet: "لم تقم بإضافة أي عملاء بعد.",
    customer: "العميل",
    contact: "اتصال",
    visits: "زيارات",
    lifetime: "حياة",
    points: "نقاط",
    credit: "رصيد",
    wallet: "محفظة",
    tier: "مستوى",
    actions: "إجراءات",
    manageSuppliers: "إدارة علاقات الموردين وتاريخ الشراء والأرصدة المستحقة.",
    addSupplier: "إضافة مورد",
    searchSuppliers: "البحث بالاسم والاتصال أو البريد الإلكتروني...",
    noSuppliersFound: "لم يتم العثور على موردين",
    noSuppliersYet: "لم تقم بإضافة أي موردين بعد.",
    due: "مستحق",
    settled: "تمت التسوية",
    itemsSupplied: "العناصر الموردة",
    manageSales: "كل معاملة عبر جميع السجلات الخاصة بك.",
    searchSales: "البحث عن طريق الفاتورة أو العميل...",
    noSalesFound: "لم يتم العثور على مبيعات",
    noSalesYet: "لم يتم تسجيل أي معاملات بعد.",
    invoice: "الفاتورة",
    date: "التاريخ",
    payment: "الدفع",
    sync: "مزامنة",
    total: "الإجمالي",
    salesReturns: "عائدات المبيعات",
    manageReturns: "المبالغ المستردة والاستبدالات الصادرة للعملاء.",
    processReturn: "معالجة الإرجاع",
    searchReturns: "البحث حسب المرجع أو العميل...",
    noReturnsFound: "لم يتم العثور على مرتجعات",
    noReturnsYet: "لم يتم تسجيل أي عائدات مبيعات بعد.",
    ref: "مرجع",
    reason: "السبب",
    refund: "استرداد",
    purchases: "مشتريات",
    managePurchases: "المخزون الوارد من الموردين وأوامر الشراء.",
    newPurchase: "شراء جديد",
    searchPurchases: "البحث عن طريق أمر الشراء أو المورد...",
    noPurchasesFound: "لم يتم العثور على مشتريات",
    noPurchasesYet: "لم يتم إنشاء أي أوامر شراء بعد.",
    po: "أمر شراء",
    supplier: "مورد",
    expenses: "المصروفات",
    manageExpenses: "تتبع تكاليف التشغيل عبر جميع الفئات.",
    totalExpenses: "إجمالي المصروفات",
    largestCategory: "أكبر فئة",
    pending: "قيد الانتظار",
    addExpense: "إضافة مصروف",
    searchExpenses: "البحث عن طريق الفئة أو الوصف...",
    noExpensesFound: "لم يتم العثور على مصروفات",
    noExpensesYet: "لم يتم تسجيل أي مصروفات بعد.",
    description: "الوصف",
    amount: "المبلغ",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    closeRegister: "إغلاق السجل",
    notifications: "الإشعارات",
    help: "مركز المساعدة",
    storeInfo: "معلومات المتجر",
    storeName: "اسم المتجر",
    taxId: "الرقم الضريبي / الرقم المميز",
    address: "العنوان",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    currency: "العملة",
    billing: "الفواتير",
    appearance: "المظهر",
    receipts: "الإيصالات",
    paymentMethods: "طرق الدفع",
    taxes: "الضرائب",
    users: "المستخدمين والأدوار",
    active: "نشط",
    inactive: "غير نشط",
    newSale: "بيع جديد",
    overview: "نظرة عامة",
    catalog: "فهرس",
    brands: "العلامات التجارية",
    units: "الوحدات",
    stock: "المخزون",
    inventory: "الجرد",
    adjustments: "التعديلات",
    transfers: "التحويلات",
    stockHistory: "سجل المخزون",
    tradeB2B: "التجارة والشركات",
    purchaseReturns: "مرتجعات المشتريات",
    salesInvoices: "فواتير المبيعات",
    quotations: "عروض الأسعار",
    deliveryChallans: "إيصالات التسليم",
    people: "الأشخاص",
    employees: "الموظفون",
    finance: "المالية والحسابات",
    accounts: "دليل الحسابات",
    accounting_reports: "تقارير المحاسبة",
    reports: "التقارير المالية",
    services: "الخدمات",
    repairs: "أوراق عمل الإصلاح",
    subscriptions: "الاشتراكات",
    rentals: "تأجير المعدات",
    marketing: "التسويق",
    coupons: "الكوبونات",
    giftCards: "بطاقات الهدايا",
    loyalty: "الولاء",
    promotions: "العروض الترويجية",
    system: "النظام",
    superAdmin: "المدير المتميز",
    clientPortal: "بوابة العميل",
    activityLog: "سجل النشاط",
    billingSales: "الفواتير والمبيعات",
    inventoryCatalog: "المخزون والكتالوج",
    purchasesSuppliers: "المشتريات والموردين",
    customersLoyalty: "العملاء ودفتر الحسابات",
    accountsExpenses: "الحسابات والمصروفات",
    servicesOperations: "الخدمات والعمليات",
    settingsSystem: "المتجر والإعدادات",
    salesFulfillment: "المبيعات والتنفيذ",
    purchasesVendors: "المشتريات والموردين",
    customersMarketing: "العملاء والتسويق",
    financeAccounts: "المالية والحسابات",
    administration: "الإدارة",
    productsCatalog: "كتالوج المنتجات",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    pos: "पीओएस टर्मिनल",
    products: "उत्पाद",
    categories: "श्रेणियां",
    customers: "ग्राहक खाता",
    suppliers: "आपूर्तिकर्ता",
    sales: "बिक्री इतिहास",
    settings: "सेटिंग्स",
    search: "खोजें...",
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    add: "नया जोड़ें",
    status: "स्थिति",
    price: "मूल्य",
    checkout: "चेकआउट",
    welcome: "स्वागत है",
    trialDaysLeft: "दिन ट्रायल शेष",
    emailVerificationRequired: "ईमेल सत्यापन आवश्यक है",
    verifyEmail: "ईमेल सत्यापित करें",
    otpSentNotice: "अपने ईमेल पर भेजा गया 6-अंकों का ओटीपी दर्ज करें।",
    language: "भाषा",
    country: "देश",
    countryCode: "कंट्री कोड",
    timezone: "टाइमज़ोन",
    dateFormat: "तारीख प्रारूप",
    manageCatalog: "अपना पूरा SKU कैटलॉग, मूल्य निर्धारण और स्टॉक सीमा प्रबंधित करें।",
    addProduct: "उत्पाद जोड़ें",
    appointments: "अपॉइंटमेंट",
    tables: "टेबल",
    kitchen: "रसोई",
    searchProducts: "नाम, SKU या बारकोड से खोजें...",
    noProductsFound: "कोई उत्पाद नहीं मिला",
    adjustSearch: "अपनी खोज को समायोजित करने का प्रयास करें।",
    noProductsYet: "आपने अभी तक कोई उत्पाद नहीं जोड़ा है।",
    product: "उत्पाद",
    sku: "एसकेयू",
    category: "श्रेणी",
    brand: "ब्रांड",
    unitType: "इकाई प्रकार",
    selectCategory: "श्रेणी चुनें...",
    selectBrand: "ब्रांड चुनें...",
    selectUnit: "इकाई चुनें...",
    selectVariant: "वेरिएंट चुनें",
    addToCart: "कार्ट में जोड़ें",
    filters: "फ़िल्टर",
    spent: "कुल खरीदारी",
    customerType: "ग्राहक प्रकार",
    items: "वस्तुएं",
    manageCustomers: "ग्राहक संबंध, वफादारी और लेजर प्रबंधित करें।",
    addCustomer: "ग्राहक जोड़ें",
    searchCustomers: "नाम, ईमेल या फोन द्वारा खोजें...",
    noCustomersFound: "कोई ग्राहक नहीं मिला",
    noCustomersYet: "आपने अभी तक कोई ग्राहक नहीं जोड़ा है।",
    customer: "ग्राहक",
    contact: "संपर्क",
    visits: "विज़िट",
    lifetime: "आजीवन",
    points: "पॉइंट्स",
    credit: "क्रेडिट",
    wallet: "बटुआ",
    tier: "श्रेणी",
    actions: "क्रिया",
    manageSuppliers: "विक्रेता संबंध, खरीद इतिहास और बकाया शेष प्रबंधित करें।",
    addSupplier: "आपूर्तिकर्ता जोड़ें",
    searchSuppliers: "नाम, संपर्क या ईमेल द्वारा खोजें...",
    noSuppliersFound: "कोई आपूर्तिकर्ता नहीं मिला",
    noSuppliersYet: "आपने अभी तक कोई आपूर्तिकर्ता नहीं जोड़ा है।",
    due: "बकाया",
    settled: "निपटान",
    itemsSupplied: "आपूर्ति की गई वस्तुएं",
    manageSales: "आपके सभी रजिस्टरों में प्रत्येक लेनदेन।",
    searchSales: "चालान या ग्राहक द्वारा खोजें...",
    noSalesFound: "कोई बिक्री नहीं मिली",
    noSalesYet: "अभी तक कोई लेनदेन रिकॉर्ड नहीं किया गया है।",
    invoice: "बीजक",
    date: "तारीख",
    payment: "भुगतान",
    sync: "सिंक",
    total: "कुल",
    salesReturns: "बिक्री वापसी",
    manageReturns: "ग्राहकों को जारी किए गए रिफंड और एक्सचेंज।",
    processReturn: "वापसी प्रक्रिया",
    searchReturns: "संदर्भ या ग्राहक द्वारा खोजें...",
    noReturnsFound: "कोई रिटर्न नहीं मिला",
    noReturnsYet: "अभी तक कोई बिक्री रिटर्न दर्ज नहीं किया गया है।",
    ref: "संदर्भ",
    reason: "कारण",
    refund: "धनवापसी",
    purchases: "खरीद",
    managePurchases: "आपूर्तिकर्ताओं और खरीद आदेशों से आने वाली इन्वेंट्री।",
    newPurchase: "नई खरीद",
    searchPurchases: "पीओ या आपूर्तिकर्ता द्वारा खोजें...",
    noPurchasesFound: "कोई खरीद नहीं मिली",
    noPurchasesYet: "अभी तक कोई खरीद आदेश नहीं बनाया गया है।",
    po: "पीओ",
    supplier: "आपूर्तिकर्ता",
    expenses: "खर्च",
    manageExpenses: "सभी श्रेणियों में परिचालन लागत ट्रैक करें।",
    totalExpenses: "कुल खर्च",
    largestCategory: "सबसे बड़ी श्रेणी",
    pending: "लंबित",
    addExpense: "खर्च जोड़ें",
    searchExpenses: "श्रेणी या विवरण द्वारा खोजें...",
    noExpensesFound: "कोई खर्च नहीं मिला",
    noExpensesYet: "अभी तक कोई खर्च दर्ज नहीं किया गया है।",
    description: "विवरण",
    amount: "रकम",
    profile: "प्रोफ़ाइल",
    logout: "लॉग आउट",
    closeRegister: "रजिस्टर बंद करें",
    notifications: "सूचनाएं",
    help: "सहायता केंद्र",
    storeInfo: "स्टोर की जानकारी",
    storeName: "स्टोर का नाम",
    taxId: "जीएसटीआईएन / टैक्स आईडी",
    address: "पता",
    phone: "फ़ोन",
    email: "ईमेल",
    currency: "मुद्रा",
    billing: "बिलिंग",
    appearance: "दिखावट",
    receipts: "रसीदें",
    paymentMethods: "भुगतान के तरीके",
    taxes: "कर (टैक्स)",
    users: "उपयोगकर्ता और भूमिकाएँ",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    newSale: "नई बिक्री",
    overview: "अवलोकन",
    catalog: "कैटलॉग",
    brands: "ब्रांड",
    units: "इकाइयाँ",
    stock: "स्टॉक",
    inventory: "इन्वेंटरी",
    adjustments: "समायोजन",
    transfers: "स्थानांतरण",
    stockHistory: "स्टॉक इतिहास",
    tradeB2B: "व्यापार और बी2बी",
    purchaseReturns: "खरीद वापसी",
    salesInvoices: "बिक्री चालान",
    quotations: "कोटेशन",
    deliveryChallans: "डिलीवरी चालान",
    people: "लोग",
    employees: "कर्मचारी",
    finance: "वित्त और खाते",
    accounts: "खातों का चार्ट",
    accounting_reports: "लेखा रिपोर्ट",
    reports: "वित्तीय रिपोर्ट",
    services: "सेवाएं",
    repairs: "मरम्मत जॉब शीट",
    subscriptions: "सदस्यता",
    rentals: "किराये पर देना",
    marketing: "मार्केटिंग",
    coupons: "कूपन",
    giftCards: "गिफ्ट कार्ड",
    loyalty: "वफादारी",
    promotions: "प्रचार",
    system: "सिस्टम",
    superAdmin: "सुपर एडमिन",
    clientPortal: "ग्राहक पोर्टल",
    activityLog: "गतिविधि लॉग",
    billingSales: "बिलिंग एवं बिक्री",
    inventoryCatalog: "इन्वेंट्री एवं स्टॉक",
    purchasesSuppliers: "खरीददारी एवं सप्लायर",
    customersLoyalty: "ग्राहक एवं खाता",
    accountsExpenses: "हिसाब-किताब एवं खर्च",
    servicesOperations: "सेवाएं एवं संचालन",
    settingsSystem: "स्टोर एवं सेटिंग्स",
    salesFulfillment: "बिक्री और पूर्ति",
    purchasesVendors: "खरीद और विक्रेता",
    customersMarketing: "ग्राहक और मार्केटिंग",
    financeAccounts: "वित्त और खाते",
    administration: "प्रशासन",
    productsCatalog: "उत्पाद कैटलॉग",
  },
  zh: {
    dashboard: "仪表板",
    pos: "POS 销售终端",
    products: "商品管理",
    categories: "商品分类",
    customers: "客户账簿",
    suppliers: "供应商",
    sales: "销售历史",
    settings: "系统设置",
    search: "搜索...",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    add: "新增",
    status: "状态",
    price: "价格",
    checkout: "结账",
    welcome: "欢迎回来",
    trialDaysLeft: "天试用剩余",
    emailVerificationRequired: "需要验证电子邮件",
    verifyEmail: "验证电子邮件",
    otpSentNotice: "请输入发送至您邮箱的6位验证码。",
    language: "语言",
    country: "国家/地区",
    countryCode: "国家/地区代码",
    timezone: "时区",
    dateFormat: "日期格式",
    manageCatalog: "管理您的完整 SKU 目录、定价和库存阈值。",
    addProduct: "添加产品",
    appointments: "预约",
    tables: "餐桌",
    kitchen: "厨房",
    searchProducts: "按名称、SKU 或条形码搜索...",
    noProductsFound: "未找到产品",
    adjustSearch: "尝试调整您的搜索。",
    noProductsYet: "您还没有添加任何产品。",
    product: "产品",
    sku: "SKU",
    category: "分类",
    brand: "品牌",
    unitType: "单位类型",
    selectCategory: "选择类别...",
    selectBrand: "选择品牌...",
    selectUnit: "选择单位...",
    selectVariant: "选择变体",
    addToCart: "加入购物车",
    filters: "筛选",
    spent: "总消费",
    customerType: "客户类型",
    items: "项目",
    manageCustomers: "管理客户关系、忠诚度和分类账。",
    addCustomer: "添加客户",
    searchCustomers: "按名称、电子邮件或电话搜索...",
    noCustomersFound: "未找到客户",
    noCustomersYet: "您还没有添加任何客户。",
    customer: "客户",
    contact: "联系方式",
    visits: "访问",
    lifetime: "终身",
    points: "积分",
    credit: "信用",
    wallet: "钱包",
    tier: "等级",
    actions: "操作",
    manageSuppliers: "管理供应商关系、购买历史记录和未结余额。",
    addSupplier: "添加供应商",
    searchSuppliers: "按名称、联系方式或电子邮件搜索...",
    noSuppliersFound: "未找到供应商",
    noSuppliersYet: "您还没有添加任何供应商。",
    due: "到期",
    settled: "已结算",
    itemsSupplied: "提供的物品",
    manageSales: "所有收银机的所有交易。",
    searchSales: "按发票或客户搜索...",
    noSalesFound: "未找到销售",
    noSalesYet: "尚未记录任何交易。",
    invoice: "发票",
    date: "日期",
    payment: "付款",
    sync: "同步",
    total: "总计",
    salesReturns: "销售退货",
    manageReturns: "向客户发出的退款和换货。",
    processReturn: "处理退货",
    searchReturns: "按参考或客户搜索...",
    noReturnsFound: "未找到退货",
    noReturnsYet: "尚未记录任何销售退货。",
    ref: "参考",
    reason: "原因",
    refund: "退款",
    purchases: "购买",
    managePurchases: "来自供应商和采购订单的入站库存。",
    newPurchase: "新购买",
    searchPurchases: "按采购订单或供应商搜索...",
    noPurchasesFound: "未找到购买记录",
    noPurchasesYet: "尚未创建任何采购订单。",
    po: "采购订单",
    supplier: "供应商",
    expenses: "费用",
    manageExpenses: "跨所有类别跟踪运营成本。",
    totalExpenses: "总费用",
    largestCategory: "最大类别",
    pending: "待定",
    addExpense: "添加费用",
    searchExpenses: "按类别或描述搜索...",
    noExpensesFound: "未找到费用",
    noExpensesYet: "尚未记录任何费用。",
    description: "描述",
    amount: "金额",
    profile: "个人资料",
    logout: "退出登录",
    closeRegister: "关闭收银机",
    notifications: "通知",
    help: "帮助中心",
    storeInfo: "店铺信息",
    storeName: "店名",
    taxId: "统一社会信用代码 / 税号",
    address: "地址",
    phone: "电话",
    email: "电子邮件",
    currency: "货币",
    billing: "账单",
    appearance: "外观",
    receipts: "收据",
    paymentMethods: "付款方式",
    taxes: "税收",
    users: "用户和角色",
    active: "活跃",
    inactive: "不活跃",
    newSale: "新销售",
    overview: "概览",
    catalog: "目录",
    brands: "品牌",
    units: "单位",
    stock: "库存",
    inventory: "存货",
    adjustments: "调整",
    transfers: "调拨",
    stockHistory: "库存历史",
    tradeB2B: "贸易与 B2B",
    purchaseReturns: "采购退货",
    salesInvoices: "销售发票",
    quotations: "报价单",
    deliveryChallans: "交货单",
    people: "人员",
    employees: "员工",
    finance: "财务与账户",
    accounts: "会计科目表",
    accounting_reports: "会计报告",
    reports: "财务报告",
    services: "服务",
    repairs: "维修工单",
    subscriptions: "订阅",
    rentals: "设备租赁",
    marketing: "营销",
    coupons: "优惠券",
    giftCards: "礼品卡",
    loyalty: "忠诚度",
    promotions: "促销",
    system: "系统",
    superAdmin: "超级管理员",
    clientPortal: "客户门户",
    activityLog: "活动日志",
    billingSales: "账单与销售",
    inventoryCatalog: "库存与目录",
    purchasesSuppliers: "采购与供应商",
    customersLoyalty: "客户与忠诚度",
    accountsExpenses: "账户与费用",
    servicesOperations: "服务与运营",
    settingsSystem: "店铺与设置",
    salesFulfillment: "销售与履约",
    purchasesVendors: "采购与供应商",
    customersMarketing: "客户与营销",
    financeAccounts: "财务与账户",
    administration: "管理系统",
    productsCatalog: "产品目录",
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("pos_app_language");
      if (saved) return saved as LanguageCode;
    }
    return "en";
  });

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("pos_app_language", lang);
    }
  }, []);

  const currentOption = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  const dir = currentOption.dir;

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
      document.documentElement.dir = dir;
    }
  }, [language, dir]);

  const t = useCallback(
    (key: string, fallback?: string): string => {
      return TRANSLATIONS[language]?.[key] || TRANSLATIONS["en"]?.[key] || fallback || key;
    },
    [language],
  );

  const value = useMemo(() => ({ language, setLanguage, t, dir }), [language, setLanguage, t, dir]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
