/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RepairsRouteImport } from './routes/repairs'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DeliveryChallansRouteImport } from './routes/delivery-challans'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AccountingReportsRouteImport } from './routes/accounting-reports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as PurchasesIndexRouteImport } from './routes/purchases.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesNewRouteImport } from './routes/services.new'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as SalesReturnsRouteImport } from './routes/sales.returns'
import { Route as PurchasesReturnsRouteImport } from './routes/purchases.returns'
import { Route as PurchasesNewRouteImport } from './routes/purchases.new'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as InventoryTransfersRouteImport } from './routes/inventory.transfers'
import { Route as InventoryHistoryRouteImport } from './routes/inventory.history'
import { Route as InventoryAdjustmentsRouteImport } from './routes/inventory.adjustments'
import { Route as ApiBlobRouteImport } from './routes/api/blob'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminHelpRouteImport } from './routes/admin/help'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reports.lazy').then((d) => d.Route))
const RepairsRoute = RepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/inventory.lazy').then((d) => d.Route))
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryChallansRoute = DeliveryChallansRouteImport.update({
  id: '/delivery-challans',
  path: '/delivery-challans',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingReportsRoute = AccountingReportsRouteImport.update({
  id: '/accounting-reports',
  path: '/accounting-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const PurchasesIndexRoute = PurchasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchasesRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any).lazy(() =>
  import('./routes/inventory.index.lazy').then((d) => d.Route),
)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNewRoute = ServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ServicesRoute,
} as any)
const SalesReturnsRoute = SalesReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => SalesRoute,
} as any)
const PurchasesReturnsRoute = PurchasesReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => PurchasesRoute,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasesRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryTransfersRoute = InventoryTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => InventoryRoute,
} as any).lazy(() =>
  import('./routes/inventory.transfers.lazy').then((d) => d.Route),
)
const InventoryHistoryRoute = InventoryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InventoryRoute,
} as any).lazy(() =>
  import('./routes/inventory.history.lazy').then((d) => d.Route),
)
const InventoryAdjustmentsRoute = InventoryAdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => InventoryRoute,
} as any).lazy(() =>
  import('./routes/inventory.adjustments.lazy').then((d) => d.Route),
)
const ApiBlobRoute = ApiBlobRouteImport.update({
  id: '/api/blob',
  path: '/api/blob',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/admin/help',
  path: '/admin/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting-reports': typeof AccountingReportsRoute
  '/accounts': typeof AccountsRoute
  '/activity': typeof ActivityRoute
  '/appointments': typeof AppointmentsRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/delivery-challans': typeof DeliveryChallansRoute
  '/error': typeof ErrorRoute
  '/expenses': typeof ExpensesRoute
  '/gift-cards': typeof GiftCardsRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/purchases': typeof PurchasesRouteWithChildren
  '/quotations': typeof QuotationsRoute
  '/register': typeof RegisterRoute
  '/rentals': typeof RentalsRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/suppliers': typeof SuppliersRoute
  '/tables': typeof TablesRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/blob': typeof ApiBlobRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/transfers': typeof InventoryTransfersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/purchases/returns': typeof PurchasesReturnsRoute
  '/sales/returns': typeof SalesReturnsRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/new': typeof ServicesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting-reports': typeof AccountingReportsRoute
  '/accounts': typeof AccountsRoute
  '/activity': typeof ActivityRoute
  '/appointments': typeof AppointmentsRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/delivery-challans': typeof DeliveryChallansRoute
  '/error': typeof ErrorRoute
  '/expenses': typeof ExpensesRoute
  '/gift-cards': typeof GiftCardsRoute
  '/help': typeof HelpRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/pos': typeof PosRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/quotations': typeof QuotationsRoute
  '/register': typeof RegisterRoute
  '/rentals': typeof RentalsRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/suppliers': typeof SuppliersRoute
  '/tables': typeof TablesRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/blob': typeof ApiBlobRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/transfers': typeof InventoryTransfersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/purchases/returns': typeof PurchasesReturnsRoute
  '/sales/returns': typeof SalesReturnsRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/new': typeof ServicesNewRoute
  '/admin': typeof AdminIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/products': typeof ProductsIndexRoute
  '/purchases': typeof PurchasesIndexRoute
  '/sales': typeof SalesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting-reports': typeof AccountingReportsRoute
  '/accounts': typeof AccountsRoute
  '/activity': typeof ActivityRoute
  '/appointments': typeof AppointmentsRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/delivery-challans': typeof DeliveryChallansRoute
  '/error': typeof ErrorRoute
  '/expenses': typeof ExpensesRoute
  '/gift-cards': typeof GiftCardsRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/portal': typeof PortalRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/purchases': typeof PurchasesRouteWithChildren
  '/quotations': typeof QuotationsRoute
  '/register': typeof RegisterRoute
  '/rentals': typeof RentalsRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/suppliers': typeof SuppliersRoute
  '/tables': typeof TablesRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/blob': typeof ApiBlobRoute
  '/inventory/adjustments': typeof InventoryAdjustmentsRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/transfers': typeof InventoryTransfersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/purchases/returns': typeof PurchasesReturnsRoute
  '/sales/returns': typeof SalesReturnsRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/new': typeof ServicesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting-reports'
    | '/accounts'
    | '/activity'
    | '/appointments'
    | '/brands'
    | '/categories'
    | '/coupons'
    | '/customers'
    | '/delivery-challans'
    | '/error'
    | '/expenses'
    | '/gift-cards'
    | '/help'
    | '/inventory'
    | '/kitchen'
    | '/login'
    | '/loyalty'
    | '/notifications'
    | '/portal'
    | '/pos'
    | '/products'
    | '/profile'
    | '/promotions'
    | '/purchases'
    | '/quotations'
    | '/register'
    | '/rentals'
    | '/repairs'
    | '/reports'
    | '/sales'
    | '/services'
    | '/settings'
    | '/subscriptions'
    | '/suppliers'
    | '/tables'
    | '/units'
    | '/users'
    | '/verify-email'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/help'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/reviews'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/users'
    | '/api/blob'
    | '/inventory/adjustments'
    | '/inventory/history'
    | '/inventory/transfers'
    | '/invite/$token'
    | '/products/$productId'
    | '/products/new'
    | '/purchases/new'
    | '/purchases/returns'
    | '/sales/returns'
    | '/services/$serviceId'
    | '/services/new'
    | '/admin/'
    | '/inventory/'
    | '/products/'
    | '/purchases/'
    | '/sales/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting-reports'
    | '/accounts'
    | '/activity'
    | '/appointments'
    | '/brands'
    | '/categories'
    | '/coupons'
    | '/customers'
    | '/delivery-challans'
    | '/error'
    | '/expenses'
    | '/gift-cards'
    | '/help'
    | '/kitchen'
    | '/login'
    | '/loyalty'
    | '/notifications'
    | '/portal'
    | '/pos'
    | '/profile'
    | '/promotions'
    | '/quotations'
    | '/register'
    | '/rentals'
    | '/repairs'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/suppliers'
    | '/tables'
    | '/units'
    | '/users'
    | '/verify-email'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/help'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/reviews'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/users'
    | '/api/blob'
    | '/inventory/adjustments'
    | '/inventory/history'
    | '/inventory/transfers'
    | '/invite/$token'
    | '/products/$productId'
    | '/products/new'
    | '/purchases/new'
    | '/purchases/returns'
    | '/sales/returns'
    | '/services/$serviceId'
    | '/services/new'
    | '/admin'
    | '/inventory'
    | '/products'
    | '/purchases'
    | '/sales'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/accounting-reports'
    | '/accounts'
    | '/activity'
    | '/appointments'
    | '/brands'
    | '/categories'
    | '/coupons'
    | '/customers'
    | '/delivery-challans'
    | '/error'
    | '/expenses'
    | '/gift-cards'
    | '/help'
    | '/inventory'
    | '/kitchen'
    | '/login'
    | '/loyalty'
    | '/notifications'
    | '/portal'
    | '/pos'
    | '/products'
    | '/profile'
    | '/promotions'
    | '/purchases'
    | '/quotations'
    | '/register'
    | '/rentals'
    | '/repairs'
    | '/reports'
    | '/sales'
    | '/services'
    | '/settings'
    | '/subscriptions'
    | '/suppliers'
    | '/tables'
    | '/units'
    | '/users'
    | '/verify-email'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/help'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/reviews'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/users'
    | '/api/blob'
    | '/inventory/adjustments'
    | '/inventory/history'
    | '/inventory/transfers'
    | '/invite/$token'
    | '/products/$productId'
    | '/products/new'
    | '/purchases/new'
    | '/purchases/returns'
    | '/sales/returns'
    | '/services/$serviceId'
    | '/services/new'
    | '/admin/'
    | '/inventory/'
    | '/products/'
    | '/purchases/'
    | '/sales/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingReportsRoute: typeof AccountingReportsRoute
  AccountsRoute: typeof AccountsRoute
  ActivityRoute: typeof ActivityRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BrandsRoute: typeof BrandsRoute
  CategoriesRoute: typeof CategoriesRoute
  CouponsRoute: typeof CouponsRoute
  CustomersRoute: typeof CustomersRoute
  DeliveryChallansRoute: typeof DeliveryChallansRoute
  ErrorRoute: typeof ErrorRoute
  ExpensesRoute: typeof ExpensesRoute
  GiftCardsRoute: typeof GiftCardsRoute
  HelpRoute: typeof HelpRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  NotificationsRoute: typeof NotificationsRoute
  PortalRoute: typeof PortalRoute
  PosRoute: typeof PosRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  PurchasesRoute: typeof PurchasesRouteWithChildren
  QuotationsRoute: typeof QuotationsRoute
  RegisterRoute: typeof RegisterRoute
  RentalsRoute: typeof RentalsRoute
  RepairsRoute: typeof RepairsRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SuppliersRoute: typeof SuppliersRoute
  TablesRoute: typeof TablesRoute
  UnitsRoute: typeof UnitsRoute
  UsersRoute: typeof UsersRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiBlobRoute: typeof ApiBlobRoute
  InviteTokenRoute: typeof InviteTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs': {
      id: '/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof RepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-challans': {
      id: '/delivery-challans'
      path: '/delivery-challans'
      fullPath: '/delivery-challans'
      preLoaderRoute: typeof DeliveryChallansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-reports': {
      id: '/accounting-reports'
      path: '/accounting-reports'
      fullPath: '/accounting-reports'
      preLoaderRoute: typeof AccountingReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/purchases/': {
      id: '/purchases/'
      path: '/'
      fullPath: '/purchases/'
      preLoaderRoute: typeof PurchasesIndexRouteImport
      parentRoute: typeof PurchasesRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/new': {
      id: '/services/new'
      path: '/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof ServicesNewRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/sales/returns': {
      id: '/sales/returns'
      path: '/returns'
      fullPath: '/sales/returns'
      preLoaderRoute: typeof SalesReturnsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/purchases/returns': {
      id: '/purchases/returns'
      path: '/returns'
      fullPath: '/purchases/returns'
      preLoaderRoute: typeof PurchasesReturnsRouteImport
      parentRoute: typeof PurchasesRoute
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof PurchasesRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/transfers': {
      id: '/inventory/transfers'
      path: '/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof InventoryTransfersRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/history': {
      id: '/inventory/history'
      path: '/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof InventoryHistoryRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/adjustments': {
      id: '/inventory/adjustments'
      path: '/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof InventoryAdjustmentsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/api/blob': {
      id: '/api/blob'
      path: '/api/blob'
      fullPath: '/api/blob'
      preLoaderRoute: typeof ApiBlobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/admin/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InventoryRouteChildren {
  InventoryAdjustmentsRoute: typeof InventoryAdjustmentsRoute
  InventoryHistoryRoute: typeof InventoryHistoryRoute
  InventoryTransfersRoute: typeof InventoryTransfersRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryAdjustmentsRoute: InventoryAdjustmentsRoute,
  InventoryHistoryRoute: InventoryHistoryRoute,
  InventoryTransfersRoute: InventoryTransfersRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface PurchasesRouteChildren {
  PurchasesNewRoute: typeof PurchasesNewRoute
  PurchasesReturnsRoute: typeof PurchasesReturnsRoute
  PurchasesIndexRoute: typeof PurchasesIndexRoute
}

const PurchasesRouteChildren: PurchasesRouteChildren = {
  PurchasesNewRoute: PurchasesNewRoute,
  PurchasesReturnsRoute: PurchasesReturnsRoute,
  PurchasesIndexRoute: PurchasesIndexRoute,
}

const PurchasesRouteWithChildren = PurchasesRoute._addFileChildren(
  PurchasesRouteChildren,
)

interface SalesRouteChildren {
  SalesReturnsRoute: typeof SalesReturnsRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesReturnsRoute: SalesReturnsRoute,
  SalesIndexRoute: SalesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

interface ServicesRouteChildren {
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  ServicesNewRoute: typeof ServicesNewRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  ServicesNewRoute: ServicesNewRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingReportsRoute: AccountingReportsRoute,
  AccountsRoute: AccountsRoute,
  ActivityRoute: ActivityRoute,
  AppointmentsRoute: AppointmentsRoute,
  BrandsRoute: BrandsRoute,
  CategoriesRoute: CategoriesRoute,
  CouponsRoute: CouponsRoute,
  CustomersRoute: CustomersRoute,
  DeliveryChallansRoute: DeliveryChallansRoute,
  ErrorRoute: ErrorRoute,
  ExpensesRoute: ExpensesRoute,
  GiftCardsRoute: GiftCardsRoute,
  HelpRoute: HelpRoute,
  InventoryRoute: InventoryRouteWithChildren,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  NotificationsRoute: NotificationsRoute,
  PortalRoute: PortalRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  PurchasesRoute: PurchasesRouteWithChildren,
  QuotationsRoute: QuotationsRoute,
  RegisterRoute: RegisterRoute,
  RentalsRoute: RentalsRoute,
  RepairsRoute: RepairsRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SuppliersRoute: SuppliersRoute,
  TablesRoute: TablesRoute,
  UnitsRoute: UnitsRoute,
  UsersRoute: UsersRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiBlobRoute: ApiBlobRoute,
  InviteTokenRoute: InviteTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
